// Code generated by codesjoy-modelgen. DO NOT EDIT.

package demo

import (
	aipsql "github.com/codesjoy/pkg/basic/aipsql"
)

// User is a generated GORM model for table "users".
type User struct {
	ID        int64   `gorm:"column:id;primaryKey" json:"id"`
	Name      *string `gorm:"column:name" json:"name"`
	UpdatedAt int64   `gorm:"column:updated_at;autoUpdateTime:milli" json:"updated_at"`
}

// TableName returns the database table name for User.
func (User) TableName() string {
	return "users"
}

// AIPTable builds the aipsql.Table mapped to "users".
func (User) AIPTable() *aipsql.Table {
	table := aipsql.NewTable().WithColumns(
		aipsql.NewColumn().
			WithFieldPath("id").
			WithDatabaseName("id").
			Filterable().
			Sortable().
			Build(),
		aipsql.NewColumn().
			WithFieldPath("name").
			WithDatabaseName("name").
			Filterable().
			WithMatchModes(aipsql.MatchModeExact).
			Build(),
		aipsql.NewColumn().
			WithFieldPath("updated_at").
			WithDatabaseName("updated_at").
			Filterable().
			Sortable().
			Build(),
	).Build()
	table.CompositeIndexes = []aipsql.CompositeIndex{
		{
			Name:    "idx_users_updated_at_id",
			Columns: []string{"updated_at", "id"},
		},
	}
	return table
}

// NewUserAIPTable keeps compatibility with package-level AIP table builders.
func NewUserAIPTable() *aipsql.Table {
	return User{}.AIPTable()
}
