// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codesjoy/example/order/v1/order.proto

package orderv1

import (
	_ "github.com/codesjoy/pkg/proto/codesjoy/ddd/event/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_codesjoy_example_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_codesjoy_example_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_codesjoy_example_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AuditPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditPing) Reset() {
	*x = AuditPing{}
	mi := &file_codesjoy_example_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditPing) ProtoMessage() {}

func (x *AuditPing) ProtoReflect() protoreflect.Message {
	mi := &file_codesjoy_example_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditPing.ProtoReflect.Descriptor instead.
func (*AuditPing) Descriptor() ([]byte, []int) {
	return file_codesjoy_example_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *AuditPing) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

var File_codesjoy_example_order_v1_order_proto protoreflect.FileDescriptor

const file_codesjoy_example_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"%codesjoy/example/order/v1/order.proto\x12\x19codesjoy.example.order.v1\x1a!codesjoy/ddd/event/v1/event.proto\"a\n" +
	"\fOrderCreated\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xb8E\x01R\x02id\x12\x1e\n" +
	"\border_id\x18\x02 \x01(\tB\x03\xc0E\x01R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId:\x03\xb2E\x00\"2\n" +
	"\tAuditPing\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor:\x0f\xb2E\f\n" +
	"\n" +
	"audit.pingBlZjgithub.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1b\x06proto3"

var (
	file_codesjoy_example_order_v1_order_proto_rawDescOnce sync.Once
	file_codesjoy_example_order_v1_order_proto_rawDescData []byte
)

func file_codesjoy_example_order_v1_order_proto_rawDescGZIP() []byte {
	file_codesjoy_example_order_v1_order_proto_rawDescOnce.Do(func() {
		file_codesjoy_example_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codesjoy_example_order_v1_order_proto_rawDesc), len(file_codesjoy_example_order_v1_order_proto_rawDesc)))
	})
	return file_codesjoy_example_order_v1_order_proto_rawDescData
}

var file_codesjoy_example_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codesjoy_example_order_v1_order_proto_goTypes = []any{
	(*OrderCreated)(nil), // 0: codesjoy.example.order.v1.OrderCreated
	(*AuditPing)(nil),    // 1: codesjoy.example.order.v1.AuditPing
}
var file_codesjoy_example_order_v1_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codesjoy_example_order_v1_order_proto_init() }
func file_codesjoy_example_order_v1_order_proto_init() {
	if File_codesjoy_example_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codesjoy_example_order_v1_order_proto_rawDesc), len(file_codesjoy_example_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codesjoy_example_order_v1_order_proto_goTypes,
		DependencyIndexes: file_codesjoy_example_order_v1_order_proto_depIdxs,
		MessageInfos:      file_codesjoy_example_order_v1_order_proto_msgTypes,
	}.Build()
	File_codesjoy_example_order_v1_order_proto = out.File
	file_codesjoy_example_order_v1_order_proto_goTypes = nil
	file_codesjoy_example_order_v1_order_proto_depIdxs = nil
}
