// Copyright 2026 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aipsql

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// EncodeSeekPageToken encodes seek token payload as URL-safe base64 JSON.
func EncodeSeekPageToken(token SeekPageToken) (string, error) {
	if token.TieBreakerValue == "" {
		return "", fmt.Errorf("tie breaker value is required")
	}
	bytes, err := json.Marshal(token)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(bytes), nil
}

// DecodeSeekPageToken decodes a token generated by EncodeSeekPageToken.
func DecodeSeekPageToken(encoded string) (SeekPageToken, error) {
	tokenText := strings.TrimSpace(encoded)
	if tokenText == "" {
		return SeekPageToken{}, fmt.Errorf("page token is empty")
	}
	bytes, err := base64.RawURLEncoding.DecodeString(tokenText)
	if err != nil {
		return SeekPageToken{}, fmt.Errorf("invalid page token encoding: %w", err)
	}
	var token SeekPageToken
	if err := json.Unmarshal(bytes, &token); err != nil {
		return SeekPageToken{}, fmt.Errorf("invalid page token payload: %w", err)
	}
	if token.TieBreakerValue == "" {
		return SeekPageToken{}, fmt.Errorf("invalid page token: tie breaker value is required")
	}
	return token, nil
}

// EncodeOffsetPageToken encodes an offset as a page token.
func EncodeOffsetPageToken(offset int) string {
	return strconv.Itoa(offset)
}

// DecodeOffsetPageToken decodes a token generated by EncodeOffsetPageToken.
func DecodeOffsetPageToken(token string) (int, error) {
	offset, err := strconv.Atoi(strings.TrimSpace(token))
	if err != nil {
		return 0, fmt.Errorf("invalid page token: %w", err)
	}
	if offset < 0 {
		return 0, nil
	}
	return offset, nil
}
