// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package aipsql pagination implementation.
//
// This file implements two pagination strategies:
//
//  1. Seek (cursor) pagination — Uses lexicographic comparison on ORDER BY columns
//     to jump directly to the next page. More efficient for large datasets because
//     it leverages database indexes instead of skipping rows.
//
//     Example generated SQL for ORDER BY created_at DESC, id DESC:
//     WHERE (created_at < @seek_cmp_0)
//     OR (created_at = @seek_eq_0 AND id < @seek_cmp_1)
//
//  2. Offset pagination — Uses traditional LIMIT/OFFSET. Simpler but degrades
//     with large offsets because the database must scan and discard preceding rows.
//
// Page tokens are opaque strings: seek tokens use URL-safe base64-encoded JSON,
// offset tokens are plain decimal integers.
package aipsql

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// SeekPageToken is the cursor payload used for seek pagination.
type SeekPageToken struct {
	SortValues      []string `json:"sort_values"`
	TieBreakerValue string   `json:"tie_breaker_value"`
}

// EncodeSeekPageToken encodes seek token payload as URL-safe base64 JSON.
func EncodeSeekPageToken(token SeekPageToken) (string, error) {
	if token.TieBreakerValue == "" {
		return "", fmt.Errorf("tie breaker value is required")
	}
	bytes, err := json.Marshal(token)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(bytes), nil
}

// DecodeSeekPageToken decodes a token generated by EncodeSeekPageToken.
func DecodeSeekPageToken(encoded string) (SeekPageToken, error) {
	tokenText := strings.TrimSpace(encoded)
	if tokenText == "" {
		return SeekPageToken{}, fmt.Errorf("page token is empty")
	}
	bytes, err := base64.RawURLEncoding.DecodeString(tokenText)
	if err != nil {
		return SeekPageToken{}, fmt.Errorf("invalid page token encoding: %w", err)
	}
	var token SeekPageToken
	if err := json.Unmarshal(bytes, &token); err != nil {
		return SeekPageToken{}, fmt.Errorf("invalid page token payload: %w", err)
	}
	if token.TieBreakerValue == "" {
		return SeekPageToken{}, fmt.Errorf("invalid page token: tie breaker value is required")
	}
	return token, nil
}

// EncodeOffsetPageToken encodes an offset as a page token.
func EncodeOffsetPageToken(offset int) string {
	return strconv.Itoa(offset)
}

// DecodeOffsetPageToken decodes a token generated by EncodeOffsetPageToken.
func DecodeOffsetPageToken(token string) (int, error) {
	offset, err := strconv.Atoi(strings.TrimSpace(token))
	if err != nil {
		return 0, fmt.Errorf("invalid page token: %w", err)
	}
	if offset < 0 {
		return 0, nil
	}
	return offset, nil
}

// seekBinder is a lightweight parameter binder used during seek pagination clause
// generation. It produces sequentially-named parameters (@prefix0, @prefix1, ...).
type seekBinder struct {
	prefix string
	next   int
	params []QueryParameter
}

func (b *seekBinder) bind(value string) string {
	name := b.prefix + strconv.Itoa(b.next)
	b.next++
	b.params = append(b.params, QueryParameter{Name: name, Value: value})
	return "@" + name
}

func (b *seekBinder) sortValue(column *Column, value string) (string, error) {
	switch column.columnType {
	case ColumnTypeString:
		return b.bind(value), nil
	case ColumnTypeBool:
		if strings.EqualFold(value, "true") {
			return "TRUE", nil
		}
		if strings.EqualFold(value, "false") {
			return "FALSE", nil
		}
		return "", fmt.Errorf(
			"only TRUE or FALSE can be specified as sort values for boolean fields",
		)
	default:
		return "", fmt.Errorf(
			"unsupported column type for seek pagination: %s",
			column.columnType.String(),
		)
	}
}

// BuildSeekPaginationClause generates a lexicographical seek-pagination predicate
// that can be appended to a WHERE clause.
//
// The generated predicate produces n+1 OR-connected sub-predicates (where n is the
// number of ORDER BY fields). Each sub-predicate handles one level of the lexicographic
// comparison, plus a final tie-breaker clause.
//
// Example for ORDER BY created_at DESC, id DESC with tie-breaker row_id ASC:
//
//	((created_at < @p_seek_0)
//	 OR (created_at = @p_seek_1 AND id < @p_seek_2)
//	 OR (created_at = @p_seek_3 AND id = @p_seek_4 AND row_id > @p_seek_5))
//
// The comparison direction (< vs >) is determined by each field's DESC/ASC direction.
func (t *Table) BuildSeekPaginationClause(
	order []OrderBy,
	lastSortValues []string,
	tieBreakerFieldPath FieldPath,
	lastTieBreakerValue string,
	parameterPrefix string,
	dialect SQLDialect,
) (string, []QueryParameter, error) {
	if _, err := normalizeSQLDialect(dialect); err != nil {
		return "", nil, err
	}
	if len(order) == 0 {
		return "", nil, fmt.Errorf("order must contain at least one field")
	}
	if len(order) != len(lastSortValues) {
		return "", nil, fmt.Errorf(
			"lastSortValues has %d values, expected %d values matching order fields",
			len(lastSortValues),
			len(order),
		)
	}
	for _, entry := range order {
		if entry.FieldPath.Equals(tieBreakerFieldPath) {
			return "", nil, fmt.Errorf(
				"tie breaker field %q must not already exist in order",
				tieBreakerFieldPath.String(),
			)
		}
	}

	tieBreakerColumn, err := t.SortableColumnByFieldPath(tieBreakerFieldPath)
	if err != nil {
		return "", nil, err
	}

	type seekColumn struct {
		column     *Column
		descending bool
		valueExpr  string
	}
	seekColumns := make([]seekColumn, 0, len(order))
	binder := &seekBinder{prefix: parameterPrefix}

	for i, entry := range order {
		column, err := t.SortableColumnByFieldPath(entry.FieldPath)
		if err != nil {
			return "", nil, err
		}
		valueExpr, err := binder.sortValue(column, lastSortValues[i])
		if err != nil {
			return "", nil, fmt.Errorf("sort value for field %q: %w", entry.FieldPath.String(), err)
		}
		seekColumns = append(seekColumns, seekColumn{
			column:     column,
			descending: entry.Descending,
			valueExpr:  valueExpr,
		})
	}

	tieBreakerExpr, err := binder.sortValue(tieBreakerColumn, lastTieBreakerValue)
	if err != nil {
		return "", nil, fmt.Errorf(
			"sort value for tie breaker field %q: %w",
			tieBreakerFieldPath.String(),
			err,
		)
	}

	// Build the lexicographic comparison parts. For each column position i,
	// generate: (col_0 = val_0 AND ... AND col_{i-1} = val_{i-1} AND col_i {<|>} val_i)
	parts := make([]string, 0, len(seekColumns)+1)
	for i := range seekColumns {
		var part strings.Builder
		part.WriteString("(")
		for j := 0; j < i; j++ {
			if j > 0 {
				part.WriteString(" AND ")
			}
			part.WriteString(seekColumns[j].column.databaseName)
			part.WriteString(" = ")
			part.WriteString(seekColumns[j].valueExpr)
		}
		if i > 0 {
			part.WriteString(" AND ")
		}
		part.WriteString(seekColumns[i].column.databaseName)
		if seekColumns[i].descending {
			part.WriteString(" < ")
		} else {
			part.WriteString(" > ")
		}
		part.WriteString(seekColumns[i].valueExpr)
		part.WriteString(")")
		parts = append(parts, part.String())
	}

	// Build the tie-breaker part: all sort columns equal AND tie_breaker > value.
	var tiePart strings.Builder
	tiePart.WriteString("(")
	for i, entry := range seekColumns {
		if i > 0 {
			tiePart.WriteString(" AND ")
		}
		tiePart.WriteString(entry.column.databaseName)
		tiePart.WriteString(" = ")
		tiePart.WriteString(entry.valueExpr)
	}
	if len(seekColumns) > 0 {
		tiePart.WriteString(" AND ")
	}
	tiePart.WriteString(tieBreakerColumn.databaseName)
	tiePart.WriteString(" > ")
	tiePart.WriteString(tieBreakerExpr)
	tiePart.WriteString(")")
	parts = append(parts, tiePart.String())

	return "(" + strings.Join(parts, " OR ") + ")", binder.params, nil
}

// buildLexicographicComparison generates n OR-connected conditions for Seek pagination,
// where n is the number of sort fields. Each condition represents one level of
// lexicographic comparison.
// buildLexicographicComparison generates a lexicographic comparison predicate for
// seek pagination using named parameters.
//
// For ORDER BY fields [A, B, C] with values [a, b, c], generates:
//
//	((A > @seek_cmp_0)
//	 OR (A = @seek_eq_1 AND B > @seek_cmp_2)
//	 OR (A = @seek_eq_3 AND B = @seek_eq_4 AND C > @seek_cmp_5))
//
// The direction of the comparison operator (< vs >) is determined by each field's
// Direction attribute (DESC → <, ASC → >).
func buildLexicographicComparison(
	fields []OrderByField,
	values []interface{},
) (string, []QueryParameter, error) {
	if len(fields) != len(values) {
		return "", nil, fmt.Errorf(
			"field count (%d) does not match value count (%d)",
			len(fields),
			len(values),
		)
	}
	if len(fields) == 0 {
		return "", nil, fmt.Errorf("fields cannot be empty")
	}

	estimatedParams := len(fields) * (len(fields) + 1) / 2
	params := make([]QueryParameter, 0, estimatedParams)
	clauses := make([]string, 0, len(fields))
	paramIndex := 0

	processedFields := make([]OrderByField, 0, len(fields))
	processedValues := make([]interface{}, 0, len(values))
	remainingFields := fields
	remainingValues := values

	for len(remainingFields) > 0 {
		currentField := remainingFields[0]
		currentValue := remainingValues[0]
		parts := make([]string, 0, len(processedFields)+1)

		prevFields := processedFields
		prevValues := processedValues
		for len(prevFields) > 0 {
			paramName := fmt.Sprintf("@seek_eq_%d", paramIndex)
			paramIndex++
			prevColumnName := prevFields[0].Column.databaseName
			parts = append(parts, fmt.Sprintf("%s = %s", prevColumnName, paramName))
			params = append(params, QueryParameter{Name: paramName, Value: prevValues[0]})
			prevFields = prevFields[1:]
			prevValues = prevValues[1:]
		}

		paramName := fmt.Sprintf("@seek_cmp_%d", paramIndex)
		paramIndex++
		operator := getComparisonOperator(currentField.Direction)
		parts = append(
			parts,
			fmt.Sprintf("%s %s %s", currentField.Column.databaseName, operator, paramName),
		)
		params = append(params, QueryParameter{Name: paramName, Value: currentValue})

		clauses = append(clauses, "("+strings.Join(parts, " AND ")+")")
		processedFields = append(processedFields, currentField)
		processedValues = append(processedValues, currentValue)
		remainingFields = remainingFields[1:]
		remainingValues = remainingValues[1:]
	}

	return "(" + strings.Join(clauses, " OR ") + ")", params, nil
}

// getComparisonOperator returns "<" for DESC direction (we want rows that come
// before the cursor value in descending order) and ">" for ASC.
func getComparisonOperator(direction string) string {
	if strings.ToUpper(direction) == "DESC" {
		return "<"
	}
	return ">"
}
