// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	annotationspb "google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	fmtPackage     = protogen.GoImportPath("fmt")
	stringsPackage = protogen.GoImportPath("strings")
)

type descriptorResource struct {
	resourceType string
	patterns     []string
	plural       string
	singular     string
	nameField    string
}

type messageResource struct {
	descriptorResource
	goName            string
	fullName          string
	nameFieldGoName   string
	parentDescriptors []descriptorResource
}

type parsedNameField struct {
	variable string
	goName   string
}

type registeredResource struct {
	descriptor descriptorResource
	owner      string
}

type resourceRegistry struct {
	byType    map[string]registeredResource
	byPattern map[string]registeredResource
}

type fileAnnotations struct {
	messageResources []messageResource
}

func generateFiles(gen *protogen.Plugin, features featureSet) error {
	registry, err := buildResourceRegistry(gen.Files, features)
	if err != nil {
		return err
	}

	for _, file := range gen.Files {
		if !file.Generate {
			continue
		}

		collected, err := collectFileAnnotations(file, features, registry)
		if err != nil {
			return err
		}
		if !collected.hasContent() {
			continue
		}

		g := gen.NewGeneratedFile(fileOutputFilename(file), file.GoImportPath)
		generateHeader(g, file)
		generateFileContent(g, collected)
	}
	return nil
}

func fileOutputFilename(file *protogen.File) string {
	return file.GeneratedFilenamePrefix + "_google_aip.pb.go"
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-google-aip. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func collectFileAnnotations(
	file *protogen.File,
	features featureSet,
	registry resourceRegistry,
) (fileAnnotations, error) {
	annotations := fileAnnotations{}

	for _, message := range file.Messages {
		if err := collectMessageAnnotations(message, &annotations, features, registry); err != nil {
			return fileAnnotations{}, fmt.Errorf("file %s: %w", file.Desc.Path(), err)
		}
	}

	sort.Slice(annotations.messageResources, func(i, j int) bool {
		return annotations.messageResources[i].fullName < annotations.messageResources[j].fullName
	})
	return annotations, nil
}

func collectMessageAnnotations(
	message *protogen.Message,
	annotations *fileAnnotations,
	features featureSet,
	registry resourceRegistry,
) error {
	if message.Desc.IsMapEntry() {
		return nil
	}

	if features.resources {
		resource, err := messageResourceDescriptor(message)
		if err != nil {
			return fmt.Errorf("message %s: %w", message.Desc.FullName(), err)
		}
		if resource != nil {
			resource.parentDescriptors = resourceParentDescriptors(
				resource.descriptorResource,
				registry,
			)
			annotations.messageResources = append(annotations.messageResources, *resource)
		}
	}

	for _, nested := range message.Messages {
		if err := collectMessageAnnotations(nested, annotations, features, registry); err != nil {
			return err
		}
	}
	return nil
}

func buildResourceRegistry(files []*protogen.File, features featureSet) (resourceRegistry, error) {
	registry := resourceRegistry{
		byType:    make(map[string]registeredResource),
		byPattern: make(map[string]registeredResource),
	}
	if !features.resources {
		return registry, nil
	}

	for _, file := range files {
		if err := registerFileResources(file, &registry); err != nil {
			return resourceRegistry{}, err
		}
	}
	return registry, nil
}

func registerFileResources(file *protogen.File, registry *resourceRegistry) error {
	fileResources, err := fileResourceDefinitions(file)
	if err != nil {
		return fmt.Errorf("file %s: %w", file.Desc.Path(), err)
	}
	for _, resource := range fileResources {
		if err := registry.add(resource, "file "+file.Desc.Path()); err != nil {
			return err
		}
	}

	for _, message := range file.Messages {
		if err := registerMessageResources(message, registry); err != nil {
			return fmt.Errorf("file %s: %w", file.Desc.Path(), err)
		}
	}
	return nil
}

func registerMessageResources(message *protogen.Message, registry *resourceRegistry) error {
	if message.Desc.IsMapEntry() {
		return nil
	}

	resource, err := messageResourceDescriptor(message)
	if err != nil {
		return fmt.Errorf("message %s: %w", message.Desc.FullName(), err)
	}
	if resource != nil {
		if err := registry.add(resource.descriptorResource, string(message.Desc.FullName())); err != nil {
			return err
		}
	}

	for _, nested := range message.Messages {
		if err := registerMessageResources(nested, registry); err != nil {
			return err
		}
	}
	return nil
}

func (registry *resourceRegistry) add(resource descriptorResource, owner string) error {
	if existing, ok := registry.byType[resource.resourceType]; ok {
		return fmt.Errorf(
			"duplicate resource type %q declared by %s and %s",
			resource.resourceType,
			existing.owner,
			owner,
		)
	}

	entry := registeredResource{
		descriptor: resource,
		owner:      owner,
	}
	registry.byType[resource.resourceType] = entry

	for _, pattern := range resource.patterns {
		if existing, ok := registry.byPattern[pattern]; ok &&
			existing.descriptor.resourceType != resource.resourceType {
			return fmt.Errorf(
				"duplicate resource pattern %q declared by %s and %s",
				pattern,
				existing.owner,
				owner,
			)
		}
		registry.byPattern[pattern] = entry
	}
	return nil
}

func messageResourceDescriptor(message *protogen.Message) (*messageResource, error) {
	if !proto.HasExtension(message.Desc.Options(), annotationspb.E_Resource) {
		return nil, nil
	}

	descriptor, err := asResourceDescriptor(
		proto.GetExtension(message.Desc.Options(), annotationspb.E_Resource),
	)
	if err != nil {
		return nil, err
	}
	if descriptor == nil {
		return nil, nil
	}

	resourceDescriptor := normalizeResourceDescriptor(descriptor)
	if err := validateDescriptorResource(resourceDescriptor); err != nil {
		return nil, err
	}
	nameField, err := resourceNameField(message, resourceDescriptor.nameField)
	if err != nil {
		return nil, err
	}

	resource := &messageResource{
		descriptorResource: resourceDescriptor,
		goName:             message.GoIdent.GoName,
		fullName:           string(message.Desc.FullName()),
		nameFieldGoName:    nameField.GoName,
	}
	return resource, nil
}

func fileResourceDefinitions(file *protogen.File) ([]descriptorResource, error) {
	if !proto.HasExtension(file.Desc.Options(), annotationspb.E_ResourceDefinition) {
		return nil, nil
	}

	descriptors, err := asResourceDescriptorList(
		proto.GetExtension(file.Desc.Options(), annotationspb.E_ResourceDefinition),
	)
	if err != nil {
		return nil, err
	}

	out := make([]descriptorResource, 0, len(descriptors))
	for _, descriptor := range descriptors {
		if descriptor == nil {
			continue
		}
		resource := normalizeResourceDescriptor(descriptor)
		if err := validateDescriptorResource(resource); err != nil {
			return nil, err
		}
		out = append(out, resource)
	}
	return out, nil
}

func resourceParentDescriptors(
	resource descriptorResource,
	registry resourceRegistry,
) []descriptorResource {
	descriptors := make([]descriptorResource, 0, len(resource.patterns))
	seenPatterns := make(map[string]struct{}, len(resource.patterns))
	for _, childPattern := range resource.patterns {
		parentPattern, err := parentPatternFromChildPattern(childPattern)
		if err != nil {
			return nil
		}

		parentResource, ok := registry.byPattern[parentPattern]
		if _, ok := seenPatterns[parentPattern]; ok {
			continue
		}
		seenPatterns[parentPattern] = struct{}{}

		if !ok {
			descriptors = append(descriptors, descriptorResource{
				patterns: []string{parentPattern},
			})
			continue
		}

		descriptor := parentResource.descriptor
		descriptors = append(descriptors, descriptorResource{
			resourceType: descriptor.resourceType,
			patterns:     []string{parentPattern},
			plural:       descriptor.plural,
			singular:     descriptor.singular,
			nameField:    descriptor.nameField,
		})
	}
	if len(descriptors) == 0 {
		return nil
	}
	return descriptors
}

func normalizeResourceDescriptor(descriptor *annotationspb.ResourceDescriptor) descriptorResource {
	if descriptor == nil {
		return descriptorResource{}
	}

	nameField := descriptor.GetNameField()
	if nameField == "" {
		nameField = "name"
	}
	return descriptorResource{
		resourceType: descriptor.GetType(),
		patterns:     append([]string(nil), descriptor.GetPattern()...),
		plural:       descriptor.GetPlural(),
		singular:     descriptor.GetSingular(),
		nameField:    nameField,
	}
}

func validateDescriptorResource(resource descriptorResource) error {
	if resource.resourceType == "" {
		return fmt.Errorf("resource type must not be empty")
	}
	if len(resource.patterns) == 0 {
		return fmt.Errorf("resource %q must declare at least one pattern", resource.resourceType)
	}
	for _, pattern := range resource.patterns {
		if err := validatePatternSyntax(pattern); err != nil {
			return fmt.Errorf("resource %q pattern %q: %w", resource.resourceType, pattern, err)
		}
	}
	return nil
}

func resourceNameField(message *protogen.Message, name string) (*protogen.Field, error) {
	for _, field := range message.Fields {
		if string(field.Desc.Name()) != name {
			continue
		}
		if field.Desc.Kind() != protoreflect.StringKind || field.Desc.IsList() ||
			field.Desc.IsMap() {
			return nil, fmt.Errorf(
				"resource name_field %q on message %s must target a singular string field",
				name,
				message.Desc.FullName(),
			)
		}
		return field, nil
	}
	return nil, fmt.Errorf(
		"resource name_field %q not found on message %s",
		name,
		message.Desc.FullName(),
	)
}

func validatePatternSyntax(pattern string) error {
	if pattern == "" {
		return fmt.Errorf("resource pattern must not be empty")
	}

	rawSegments := strings.Split(pattern, "/")
	seen := make(map[string]struct{}, len(rawSegments))
	for _, raw := range rawSegments {
		if raw == "" {
			return fmt.Errorf("resource pattern %q contains an empty path segment", pattern)
		}
		if strings.HasPrefix(raw, "{") || strings.HasSuffix(raw, "}") {
			if !strings.HasPrefix(raw, "{") || !strings.HasSuffix(raw, "}") {
				return fmt.Errorf(
					"resource pattern %q contains malformed variable segment %q",
					pattern,
					raw,
				)
			}
			name := strings.TrimSuffix(strings.TrimPrefix(raw, "{"), "}")
			if name == "" {
				return fmt.Errorf("resource pattern %q contains an empty variable segment", pattern)
			}
			if strings.Contains(name, "/") || strings.Contains(name, "=") {
				return fmt.Errorf(
					"resource pattern %q contains unsupported variable syntax %q",
					pattern,
					raw,
				)
			}
			if _, ok := seen[name]; ok {
				return fmt.Errorf("resource pattern %q reuses variable %q", pattern, name)
			}
			seen[name] = struct{}{}
			continue
		}
		if strings.Contains(raw, "{") || strings.Contains(raw, "}") {
			return fmt.Errorf("resource pattern %q contains malformed segment %q", pattern, raw)
		}
	}

	return nil
}

func parentPatternFromChildPattern(pattern string) (string, error) {
	segments := strings.Split(pattern, "/")
	if len(segments) < 2 {
		return "", fmt.Errorf("must contain at least 2 path segments")
	}

	lastSegment := segments[len(segments)-1]
	collectionSegment := segments[len(segments)-2]
	if !isVariablePatternSegment(lastSegment) {
		return "", fmt.Errorf("must end with a variable segment")
	}
	if isVariablePatternSegment(collectionSegment) {
		return "", fmt.Errorf("must have a literal collection segment before the final variable")
	}

	parentPattern := strings.Join(segments[:len(segments)-2], "/")
	if parentPattern == "" {
		return "", fmt.Errorf("derived parent pattern must not be empty")
	}
	return parentPattern, nil
}

func isVariablePatternSegment(segment string) bool {
	return strings.HasPrefix(segment, "{") && strings.HasSuffix(segment, "}")
}

func asResourceDescriptor(value any) (*annotationspb.ResourceDescriptor, error) {
	switch typed := value.(type) {
	case *annotationspb.ResourceDescriptor:
		return typed, nil
	case annotationspb.ResourceDescriptor:
		return &typed, nil
	default:
		return nil, fmt.Errorf("unexpected resource extension type %T", value)
	}
}

func asResourceDescriptorList(value any) ([]*annotationspb.ResourceDescriptor, error) {
	switch typed := value.(type) {
	case []*annotationspb.ResourceDescriptor:
		return typed, nil
	case *[]*annotationspb.ResourceDescriptor:
		if typed == nil {
			return nil, nil
		}
		return *typed, nil
	case []annotationspb.ResourceDescriptor:
		out := make([]*annotationspb.ResourceDescriptor, 0, len(typed))
		for i := range typed {
			out = append(out, &typed[i])
		}
		return out, nil
	default:
		return nil, fmt.Errorf("unexpected resource_definition extension type %T", value)
	}
}

func (annotations fileAnnotations) hasContent() bool {
	return len(annotations.messageResources) > 0
}

func generateFileContent(g *protogen.GeneratedFile, annotations fileAnnotations) {
	if len(annotations.messageResources) > 0 {
		generateResourcePatternConstants(g, annotations.messageResources)
		generateParsedNameTypes(g, annotations.messageResources)
		generateParsedParentTypes(g, annotations.messageResources)
		generateMessageResourceMethods(g, annotations.messageResources)
	}
}

func generateResourcePatternConstants(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		if len(resource.patterns) == 1 {
			g.P(
				"// ",
				messageResourcePatternConstName(resource, 0),
				" is a supported resource name pattern for ",
				resource.goName,
				".",
			)
			g.P(
				"const ",
				messageResourcePatternConstName(resource, 0),
				" = ",
				strconv.Quote(resource.patterns[0]),
			)
			g.P()
			continue
		}

		g.P("const (")
		for i, pattern := range resource.patterns {
			g.P(
				"\t// ",
				messageResourcePatternConstName(resource, i),
				" is a supported resource name pattern for ",
				resource.goName,
				".",
			)
			g.P("\t", messageResourcePatternConstName(resource, i), " = ", strconv.Quote(pattern))
		}
		g.P(")")
		g.P()
	}
}

func generateParsedNameTypes(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		g.P(
			"// ", messageResourceParsedNameTypeName(resource),
			" contains the typed components of a parsed ",
			resource.goName,
			" resource name.",
		)
		g.P("type ", messageResourceParsedNameTypeName(resource), " struct {")
		g.P("\tDescriptorType string")
		g.P("\tPattern string")
		for _, field := range messageResourceParsedFields(resource.patterns) {
			g.P("\t", field.goName, " string")
		}
		g.P("}")
		g.P()
	}
}

func generateParsedParentTypes(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		if len(resource.parentDescriptors) == 0 {
			continue
		}

		g.P(
			"// ", messageResourceParsedParentTypeName(resource),
			" contains the typed components of a parsed parent for ",
			resource.goName,
			".",
		)
		g.P("type ", messageResourceParsedParentTypeName(resource), " struct {")
		g.P("\tDescriptorType string")
		g.P("\tPattern string")
		for _, field := range messageResourceParsedParentFields(resource) {
			g.P("\t", field.goName, " string")
		}
		g.P("}")
		g.P()
	}
}

func generateMessageResourceMethods(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		fieldExpr := "x." + resource.nameFieldGoName
		nilReceiverError := strconv.Quote("nil *" + resource.goName + " receiver")
		parseFuncName := messageResourceParseNameFuncName(resource)
		validateFuncName := messageResourceValidateNameFuncName(resource)
		parsedTypeName := messageResourceParsedNameTypeName(resource)
		parsedFields := messageResourceParsedFields(resource.patterns)

		g.P(
			"// ", parseFuncName, " parses a ", resource.goName,
			" resource name into typed fields.",
		)
		g.P(
			"func ", parseFuncName, "(name string) (",
			parsedTypeName,
			", error) {",
		)
		g.P("\tparts := ", stdstrings(g, "Split"), `(name, "/")`)
		for i, pattern := range resource.patterns {
			g.P("\tif ", generatedPatternMatchCondition("parts", pattern), " {")
			g.P("\t\treturn ", parsedTypeName, "{")
			g.P("\t\t\tDescriptorType: ", strconv.Quote(resource.resourceType), ",")
			g.P("\t\t\tPattern: ", messageResourcePatternConstName(resource, i), ",")
			indexes := patternVariableIndexes(pattern)
			for _, field := range parsedFields {
				if index, ok := indexes[field.variable]; ok {
					g.P("\t\t\t", field.goName, ": parts[", strconv.Itoa(index), "],")
				}
			}
			g.P("\t\t}, nil")
			g.P("\t}")
		}
		g.P(
			"\treturn ", parsedTypeName, "{}, ",
			stdfmt(g, "Errorf"),
			`("resource name %q does not match type %q", name, `,
			strconv.Quote(resource.resourceType),
			")",
		)
		g.P("}")
		g.P()

		g.P(
			"// ",
			validateFuncName,
			" reports whether name is a valid ",
			resource.goName,
			" resource name.",
		)
		g.P("func ", validateFuncName, "(name string) error {")
		g.P("\t_, err := ", parseFuncName, "(name)")
		g.P("\treturn err")
		g.P("}")
		g.P()

		g.P("// ParseName parses the resource name stored on ", resource.goName, ".")
		g.P(
			"func (x *", resource.goName, ") ParseName() (",
			parsedTypeName,
			", error) {",
		)
		g.P("\tif x == nil {")
		g.P("\t\treturn ", parsedTypeName, "{}, ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\treturn ", parseFuncName, "(", fieldExpr, ")")
		g.P("}")
		g.P()

		g.P(
			"// ValidateName reports whether the resource name stored on ",
			resource.goName,
			" is valid.",
		)
		g.P("func (x *", resource.goName, ") ValidateName() error {")
		g.P("\tif x == nil {")
		g.P("\t\treturn ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\treturn ", validateFuncName, "(", fieldExpr, ")")
		g.P("}")
		g.P()

		g.P(
			"// FillNameWithPattern formats a supported resource name pattern and writes it back to ",
			resource.nameFieldGoName,
			".",
		)
		g.P(
			"func (x *",
			resource.goName,
			") FillNameWithPattern(pattern string, values map[string]string) error {",
		)
		g.P("\tif x == nil {")
		g.P("\t\treturn ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\tvar formatted string")
		g.P("\tswitch pattern {")
		for i, pattern := range resource.patterns {
			g.P("\tcase ", messageResourcePatternConstName(resource, i), ":")
			writeGeneratedFormatCase(g, pattern)
		}
		g.P("\tdefault:")
		g.P(
			"\t\treturn ", stdfmt(g, "Errorf"),
			`("pattern %q is not registered for type %q", pattern, `,
			strconv.Quote(resource.resourceType),
			")",
		)
		g.P("\t}")
		g.P("\t", fieldExpr, " = formatted")
		g.P("\treturn nil")
		g.P("}")
		g.P()

		if len(resource.patterns) == 1 {
			g.P(
				"// FillName formats the only supported resource name pattern and writes it back to ",
				resource.nameFieldGoName,
				".",
			)
			g.P("func (x *", resource.goName, ") FillName(values map[string]string) error {")
			g.P(
				"\treturn x.FillNameWithPattern(",
				messageResourcePatternConstName(resource, 0),
				", values)",
			)
			g.P("}")
			g.P()
		}

		if len(resource.parentDescriptors) == 0 {
			continue
		}

		parentParseFuncName := messageResourceParseParentFuncName(resource)
		parentValidateFuncName := messageResourceValidateParentFuncName(resource)
		parentParsedTypeName := messageResourceParsedParentTypeName(resource)
		parentParsedFields := messageResourceParsedParentFields(resource)
		parseParentError := strconv.Quote(
			"parent %q does not match any inferred parent resource for type " + resource.resourceType,
		)

		g.P(
			"// ", parentParseFuncName,
			" parses a parent resource name accepted by ",
			resource.goName,
			" into typed fields.",
		)
		g.P(
			"func ", parentParseFuncName, "(parent string) (",
			parentParsedTypeName,
			", error) {",
		)
		g.P("\tparts := ", stdstrings(g, "Split"), `(parent, "/")`)
		for _, descriptor := range resource.parentDescriptors {
			pattern := descriptor.patterns[0]
			g.P("\tif ", generatedPatternMatchCondition("parts", pattern), " {")
			g.P("\t\treturn ", parentParsedTypeName, "{")
			g.P("\t\t\tDescriptorType: ", strconv.Quote(descriptor.resourceType), ",")
			g.P("\t\t\tPattern: ", strconv.Quote(pattern), ",")
			indexes := patternVariableIndexes(pattern)
			for _, field := range parentParsedFields {
				if index, ok := indexes[field.variable]; ok {
					g.P("\t\t\t", field.goName, ": parts[", strconv.Itoa(index), "],")
				}
			}
			g.P("\t\t}, nil")
			g.P("\t}")
		}
		g.P(
			"\treturn ", parentParsedTypeName, "{}, ",
			stdfmt(g, "Errorf"),
			"(", parseParentError, ", parent)",
		)
		g.P("}")
		g.P()

		g.P(
			"// ",
			parentValidateFuncName,
			" reports whether parent is a valid parent resource name for ",
			resource.goName,
			".",
		)
		g.P("func ", parentValidateFuncName, "(parent string) error {")
		g.P("\t_, err := ", parentParseFuncName, "(parent)")
		g.P("\treturn err")
		g.P("}")
		g.P()

		g.P("// ParseParent parses a parent resource name accepted by ", resource.goName, ".")
		g.P(
			"func (x *", resource.goName, ") ParseParent(parent string) (",
			parentParsedTypeName,
			", error) {",
		)
		g.P("\tif x == nil {")
		g.P(
			"\t\treturn ",
			parentParsedTypeName,
			"{}, ",
			stdfmt(g, "Errorf"),
			"(",
			nilReceiverError,
			")",
		)
		g.P("\t}")
		g.P("\treturn ", parentParseFuncName, "(parent)")
		g.P("}")
		g.P()

		g.P(
			"// ValidateParent reports whether parent is a valid parent resource name for ",
			resource.goName,
			".",
		)
		g.P("func (x *", resource.goName, ") ValidateParent(parent string) error {")
		g.P("\tif x == nil {")
		g.P("\t\treturn ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\treturn ", parentValidateFuncName, "(parent)")
		g.P("}")
		g.P()
	}
}

func generatedPatternMatchCondition(partsExpr string, pattern string) string {
	segments := strings.Split(pattern, "/")
	conditions := []string{
		fmt.Sprintf("len(%s) == %d", partsExpr, len(segments)),
	}
	for i, segment := range segments {
		partExpr := fmt.Sprintf("%s[%d]", partsExpr, i)
		if isVariablePatternSegment(segment) {
			conditions = append(conditions, partExpr+` != ""`)
			continue
		}
		conditions = append(conditions, partExpr+" == "+strconv.Quote(segment))
	}
	return strings.Join(conditions, " && ")
}

func patternVariableIndexes(pattern string) map[string]int {
	segments := strings.Split(pattern, "/")
	indexes := make(map[string]int, len(segments))
	for i, segment := range segments {
		if !isVariablePatternSegment(segment) {
			continue
		}
		indexes[strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}")] = i
	}
	return indexes
}

func writeGeneratedFormatCase(g *protogen.GeneratedFile, pattern string) {
	segments := strings.Split(pattern, "/")
	formattedParts := make([]string, 0, len(segments))
	for i, segment := range segments {
		if !isVariablePatternSegment(segment) {
			formattedParts = append(formattedParts, strconv.Quote(segment))
			continue
		}

		variable := strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}")
		localName := "value" + strconv.Itoa(i)
		g.P(`		`, localName, `, ok := values["`, variable, `"]`)
		g.P("\t\tif !ok {")
		g.P(
			"\t\t\treturn ", stdfmt(g, "Errorf"),
			`("missing value for variable %q in pattern %q", `,
			strconv.Quote(variable),
			", pattern)",
		)
		g.P("\t\t}")
		g.P("\t\tif ", localName, ` == "" {`)
		g.P(
			"\t\t\treturn ", stdfmt(g, "Errorf"),
			`("value for variable %q in pattern %q must not be empty", `,
			strconv.Quote(variable),
			", pattern)",
		)
		g.P("\t\t}")
		g.P("\t\tif ", stdstrings(g, "Contains"), "(", localName, `, "/") {`)
		g.P(
			"\t\t\treturn ", stdfmt(g, "Errorf"),
			`("value for variable %q in pattern %q must not contain '/'", `,
			strconv.Quote(variable),
			", pattern)",
		)
		g.P("\t\t}")
		formattedParts = append(formattedParts, localName)
	}
	g.P("\t\tformatted = ", strings.Join(formattedParts, ` + "/" + `))
}

func messageResourcePatternConstName(resource messageResource, index int) string {
	base := resource.goName + "NamePattern"
	if len(resource.patterns) == 1 {
		return base
	}
	return base + strconv.Itoa(index+1)
}

func messageResourceParseNameFuncName(resource messageResource) string {
	return "Parse" + resource.goName + "Name"
}

func messageResourceValidateNameFuncName(resource messageResource) string {
	return "Validate" + resource.goName + "Name"
}

func messageResourceParsedNameTypeName(resource messageResource) string {
	return "Parsed" + resource.goName + "Name"
}

func messageResourceParseParentFuncName(resource messageResource) string {
	return "Parse" + resource.goName + "Parent"
}

func messageResourceValidateParentFuncName(resource messageResource) string {
	return "Validate" + resource.goName + "Parent"
}

func messageResourceParsedParentTypeName(resource messageResource) string {
	return "Parsed" + resource.goName + "Parent"
}

func messageResourceParsedParentFields(resource messageResource) []parsedNameField {
	patterns := make([]string, 0, len(resource.parentDescriptors))
	for _, descriptor := range resource.parentDescriptors {
		patterns = append(patterns, descriptor.patterns[0])
	}
	return messageResourceParsedFields(patterns)
}

func messageResourceParsedFields(patterns []string) []parsedNameField {
	fields := make([]parsedNameField, 0, len(patterns))
	seenVariables := make(map[string]struct{}, len(patterns))
	usedGoNames := map[string]struct{}{
		"DescriptorType": {},
		"Pattern":        {},
	}

	for _, pattern := range patterns {
		for _, variable := range patternVariables(pattern) {
			if _, ok := seenVariables[variable]; ok {
				continue
			}
			seenVariables[variable] = struct{}{}

			goName := exportedPatternVariableGoName(variable)
			if goName == "" {
				goName = "Value"
			}
			base := goName
			if _, ok := usedGoNames[goName]; ok {
				goName = base + "Value"
				for i := 2; ; i++ {
					if _, ok := usedGoNames[goName]; !ok {
						break
					}
					goName = base + "Value" + strconv.Itoa(i)
				}
			}
			usedGoNames[goName] = struct{}{}

			fields = append(fields, parsedNameField{
				variable: variable,
				goName:   goName,
			})
		}
	}

	return fields
}

func patternVariables(pattern string) []string {
	segments := strings.Split(pattern, "/")
	variables := make([]string, 0, len(segments))
	for _, segment := range segments {
		if !isVariablePatternSegment(segment) {
			continue
		}
		variables = append(variables, strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}"))
	}
	return variables
}

func exportedPatternVariableGoName(variable string) string {
	parts := strings.FieldsFunc(variable, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		return ""
	}

	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		builder.WriteRune(unicode.ToUpper(runes[0]))
		builder.WriteString(string(runes[1:]))
	}

	name := builder.String()
	if name == "" {
		return ""
	}
	if unicode.IsDigit([]rune(name)[0]) {
		return "X" + name
	}
	return name
}

func stdfmt(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(fmtPackage.Ident(name))
}

func stdstrings(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(stringsPackage.Ident(name))
}
