// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	annotationspb "google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	runtimePackage     = protogen.GoImportPath("github.com/codesjoy/pkg/tools/protoc-gen-google-aip/runtime/googleaip")
	annotationsPackage = protogen.GoImportPath("google.golang.org/genproto/googleapis/api/annotations")
	fmtPackage         = protogen.GoImportPath("fmt")
)

type descriptorResource struct {
	resourceType string
	patterns     []string
	plural       string
	singular     string
	nameField    string
}

type messageResource struct {
	descriptorResource
	goName          string
	fullName        string
	nameFieldGoName string
}

type resourceReference struct {
	messageFullName string
	fieldName       string
	resourceType    string
	childType       string
}

type messageMetadata struct {
	goName         string
	fullName       string
	resourceRefs   map[string]resourceReference
	fieldBehaviors map[string][]annotationspb.FieldBehavior
	requiredFields []string
}

type serviceMetadata struct {
	goName           string
	fullName         string
	methodSignatures map[string][][]string
}

type fileAnnotations struct {
	messageResources []messageResource

	messages []messageMetadata
	services []serviceMetadata
}

func generateFiles(gen *protogen.Plugin, features featureSet) error {
	seenResourceTypes := make(map[string]string)
	for _, file := range gen.Files {
		if !file.Generate {
			continue
		}

		collected, err := collectFileAnnotations(file, features, seenResourceTypes)
		if err != nil {
			return err
		}
		if !collected.hasContent() {
			continue
		}

		g := gen.NewGeneratedFile(fileOutputFilename(file), file.GoImportPath)
		generateHeader(g, file)
		generateFileContent(g, collected)
	}
	return nil
}

func fileOutputFilename(file *protogen.File) string {
	return file.GeneratedFilenamePrefix + "_google_aip.pb.go"
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-google-aip. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func collectFileAnnotations(
	file *protogen.File,
	features featureSet,
	seenResourceTypes map[string]string,
) (fileAnnotations, error) {
	annotations := fileAnnotations{}

	if features.resources {
		fileResources, err := fileResourceDefinitions(file)
		if err != nil {
			return fileAnnotations{}, fmt.Errorf("file %s: %w", file.Desc.Path(), err)
		}
		for _, resource := range fileResources {
			if owner, ok := seenResourceTypes[resource.resourceType]; ok {
				return fileAnnotations{}, fmt.Errorf(
					"duplicate resource type %q declared by %s and file %s",
					resource.resourceType,
					owner,
					file.Desc.Path(),
				)
			}
			seenResourceTypes[resource.resourceType] = file.Desc.Path()
		}
	}

	for _, message := range file.Messages {
		if err := collectMessageAnnotations(message, &annotations, features, seenResourceTypes); err != nil {
			return fileAnnotations{}, fmt.Errorf("file %s: %w", file.Desc.Path(), err)
		}
	}

	if features.methodSignature {
		for _, service := range file.Services {
			if err := collectServiceAnnotations(service, &annotations); err != nil {
				return fileAnnotations{}, fmt.Errorf("service %s: %w", service.Desc.FullName(), err)
			}
		}
	}

	sort.Slice(annotations.messageResources, func(i, j int) bool {
		return annotations.messageResources[i].fullName < annotations.messageResources[j].fullName
	})
	sort.Slice(annotations.messages, func(i, j int) bool {
		return annotations.messages[i].fullName < annotations.messages[j].fullName
	})
	sort.Slice(annotations.services, func(i, j int) bool {
		return annotations.services[i].fullName < annotations.services[j].fullName
	})
	return annotations, nil
}

func collectMessageAnnotations(
	message *protogen.Message,
	annotations *fileAnnotations,
	features featureSet,
	seenResourceTypes map[string]string,
) error {
	if message.Desc.IsMapEntry() {
		return nil
	}

	messageFullName := string(message.Desc.FullName())
	messageAnnotations := messageMetadata{
		goName:   message.GoIdent.GoName,
		fullName: messageFullName,
	}

	if features.resources {
		resource, err := messageResourceDescriptor(message)
		if err != nil {
			return fmt.Errorf("message %s: %w", message.Desc.FullName(), err)
		}
		if resource != nil {
			if owner, ok := seenResourceTypes[resource.resourceType]; ok {
				return fmt.Errorf(
					"duplicate resource type %q declared by %s and message %s",
					resource.resourceType,
					owner,
					message.Desc.FullName(),
				)
			}
			seenResourceTypes[resource.resourceType] = messageFullName
			annotations.messageResources = append(annotations.messageResources, *resource)
		}

		for _, field := range message.Fields {
			ref, err := resourceReferenceDescriptor(field)
			if err != nil {
				return fmt.Errorf("field %s: %w", field.Desc.FullName(), err)
			}
			if ref == nil {
				continue
			}
			if messageAnnotations.resourceRefs == nil {
				messageAnnotations.resourceRefs = make(map[string]resourceReference)
			}
			messageAnnotations.resourceRefs[ref.fieldName] = *ref
		}
	}

	if features.fieldBehavior {
		for _, field := range message.Fields {
			behaviors, err := fieldBehaviorDescriptors(field)
			if err != nil {
				return fmt.Errorf("field %s: %w", field.Desc.FullName(), err)
			}
			if len(behaviors) == 0 {
				continue
			}

			if messageAnnotations.fieldBehaviors == nil {
				messageAnnotations.fieldBehaviors = make(map[string][]annotationspb.FieldBehavior)
			}
			messageAnnotations.fieldBehaviors[string(field.Desc.Name())] = append(
				[]annotationspb.FieldBehavior(nil),
				behaviors...,
			)

			if containsRequiredFieldBehavior(behaviors) {
				messageAnnotations.requiredFields = appendUnique(
					messageAnnotations.requiredFields,
					string(field.Desc.Name()),
				)
			}
		}
	}

	if len(messageAnnotations.resourceRefs) > 0 ||
		len(messageAnnotations.fieldBehaviors) > 0 ||
		len(messageAnnotations.requiredFields) > 0 {
		annotations.messages = append(annotations.messages, messageAnnotations)
	}

	for _, nested := range message.Messages {
		if err := collectMessageAnnotations(nested, annotations, features, seenResourceTypes); err != nil {
			return err
		}
	}
	return nil
}

func collectServiceAnnotations(service *protogen.Service, annotations *fileAnnotations) error {
	methods := make(map[string][][]string)
	for _, method := range service.Methods {
		signatures, err := methodSignatureDescriptors(method)
		if err != nil {
			return fmt.Errorf("method %s: %w", method.Desc.FullName(), err)
		}
		if len(signatures) == 0 {
			continue
		}
		methods[string(method.Desc.Name())] = signatures
	}

	if len(methods) == 0 {
		return nil
	}
	annotations.services = append(annotations.services, serviceMetadata{
		goName:           service.GoName,
		fullName:         string(service.Desc.FullName()),
		methodSignatures: methods,
	})
	return nil
}

func messageResourceDescriptor(message *protogen.Message) (*messageResource, error) {
	if !proto.HasExtension(message.Desc.Options(), annotationspb.E_Resource) {
		return nil, nil
	}

	descriptor, err := asResourceDescriptor(proto.GetExtension(message.Desc.Options(), annotationspb.E_Resource))
	if err != nil {
		return nil, err
	}
	if descriptor == nil {
		return nil, nil
	}

	resourceDescriptor := normalizeResourceDescriptor(*descriptor)
	if err := validateDescriptorResource(resourceDescriptor); err != nil {
		return nil, err
	}
	nameField, err := resourceNameField(message, resourceDescriptor.nameField)
	if err != nil {
		return nil, err
	}

	resource := &messageResource{
		descriptorResource: resourceDescriptor,
		goName:             message.GoIdent.GoName,
		fullName:           string(message.Desc.FullName()),
		nameFieldGoName:    nameField.GoName,
	}
	return resource, nil
}

func fileResourceDefinitions(file *protogen.File) ([]descriptorResource, error) {
	if !proto.HasExtension(file.Desc.Options(), annotationspb.E_ResourceDefinition) {
		return nil, nil
	}

	descriptors, err := asResourceDescriptorList(proto.GetExtension(file.Desc.Options(), annotationspb.E_ResourceDefinition))
	if err != nil {
		return nil, err
	}

	out := make([]descriptorResource, 0, len(descriptors))
	for _, descriptor := range descriptors {
		if descriptor == nil {
			continue
		}
		resource := normalizeResourceDescriptor(*descriptor)
		if err := validateDescriptorResource(resource); err != nil {
			return nil, err
		}
		out = append(out, resource)
	}
	return out, nil
}

func resourceReferenceDescriptor(field *protogen.Field) (*resourceReference, error) {
	if !proto.HasExtension(field.Desc.Options(), annotationspb.E_ResourceReference) {
		return nil, nil
	}

	reference, err := asResourceReference(proto.GetExtension(field.Desc.Options(), annotationspb.E_ResourceReference))
	if err != nil {
		return nil, err
	}
	if reference == nil {
		return nil, nil
	}

	return &resourceReference{
		messageFullName: string(field.Parent.Desc.FullName()),
		fieldName:       string(field.Desc.Name()),
		resourceType:    reference.GetType(),
		childType:       reference.GetChildType(),
	}, nil
}

func fieldBehaviorDescriptors(field *protogen.Field) ([]annotationspb.FieldBehavior, error) {
	if !proto.HasExtension(field.Desc.Options(), annotationspb.E_FieldBehavior) {
		return nil, nil
	}

	raw := proto.GetExtension(field.Desc.Options(), annotationspb.E_FieldBehavior)
	switch typed := raw.(type) {
	case []annotationspb.FieldBehavior:
		return append([]annotationspb.FieldBehavior(nil), typed...), nil
	case *[]annotationspb.FieldBehavior:
		if typed == nil {
			return nil, nil
		}
		return append([]annotationspb.FieldBehavior(nil), (*typed)...), nil
	case []int32:
		out := make([]annotationspb.FieldBehavior, 0, len(typed))
		for _, item := range typed {
			out = append(out, annotationspb.FieldBehavior(item))
		}
		return out, nil
	default:
		return nil, fmt.Errorf("unexpected field_behavior extension type %T", raw)
	}
}

func methodSignatureDescriptors(method *protogen.Method) ([][]string, error) {
	if !proto.HasExtension(method.Desc.Options(), annotationspb.E_MethodSignature) {
		return nil, nil
	}

	raw := proto.GetExtension(method.Desc.Options(), annotationspb.E_MethodSignature)
	var values []string
	switch typed := raw.(type) {
	case []string:
		values = append(values, typed...)
	case *[]string:
		if typed != nil {
			values = append(values, (*typed)...)
		}
	default:
		return nil, fmt.Errorf("unexpected method_signature extension type %T", raw)
	}

	out := make([][]string, 0, len(values))
	for _, value := range values {
		parts := splitMethodSignature(value)
		if len(parts) == 0 {
			continue
		}
		out = append(out, parts)
	}
	return out, nil
}

func splitMethodSignature(value string) []string {
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		out = append(out, part)
	}
	return out
}

func normalizeResourceDescriptor(descriptor annotationspb.ResourceDescriptor) descriptorResource {
	nameField := descriptor.GetNameField()
	if nameField == "" {
		nameField = "name"
	}
	return descriptorResource{
		resourceType: descriptor.GetType(),
		patterns:     append([]string(nil), descriptor.GetPattern()...),
		plural:       descriptor.GetPlural(),
		singular:     descriptor.GetSingular(),
		nameField:    nameField,
	}
}

func validateDescriptorResource(resource descriptorResource) error {
	if resource.resourceType == "" {
		return fmt.Errorf("resource type must not be empty")
	}
	if len(resource.patterns) == 0 {
		return fmt.Errorf("resource %q must declare at least one pattern", resource.resourceType)
	}
	for _, pattern := range resource.patterns {
		if err := validatePatternSyntax(pattern); err != nil {
			return fmt.Errorf("resource %q pattern %q: %w", resource.resourceType, pattern, err)
		}
	}
	return nil
}

func resourceNameField(message *protogen.Message, name string) (*protogen.Field, error) {
	for _, field := range message.Fields {
		if string(field.Desc.Name()) != name {
			continue
		}
		if field.Desc.Kind() != protoreflect.StringKind || field.Desc.IsList() || field.Desc.IsMap() {
			return nil, fmt.Errorf(
				"resource name_field %q on message %s must target a singular string field",
				name,
				message.Desc.FullName(),
			)
		}
		return field, nil
	}
	return nil, fmt.Errorf(
		"resource name_field %q not found on message %s",
		name,
		message.Desc.FullName(),
	)
}

func validatePatternSyntax(pattern string) error {
	if pattern == "" {
		return fmt.Errorf("resource pattern must not be empty")
	}

	rawSegments := strings.Split(pattern, "/")
	seen := make(map[string]struct{}, len(rawSegments))
	for _, raw := range rawSegments {
		if raw == "" {
			return fmt.Errorf("resource pattern %q contains an empty path segment", pattern)
		}
		if strings.HasPrefix(raw, "{") || strings.HasSuffix(raw, "}") {
			if !strings.HasPrefix(raw, "{") || !strings.HasSuffix(raw, "}") {
				return fmt.Errorf("resource pattern %q contains malformed variable segment %q", pattern, raw)
			}
			name := strings.TrimSuffix(strings.TrimPrefix(raw, "{"), "}")
			if name == "" {
				return fmt.Errorf("resource pattern %q contains an empty variable segment", pattern)
			}
			if strings.Contains(name, "/") || strings.Contains(name, "=") {
				return fmt.Errorf("resource pattern %q contains unsupported variable syntax %q", pattern, raw)
			}
			if _, ok := seen[name]; ok {
				return fmt.Errorf("resource pattern %q reuses variable %q", pattern, name)
			}
			seen[name] = struct{}{}
			continue
		}
		if strings.Contains(raw, "{") || strings.Contains(raw, "}") {
			return fmt.Errorf("resource pattern %q contains malformed segment %q", pattern, raw)
		}
	}

	return nil
}

func containsRequiredFieldBehavior(values []annotationspb.FieldBehavior) bool {
	for _, value := range values {
		if value == annotationspb.FieldBehavior_REQUIRED {
			return true
		}
	}
	return false
}

func appendUnique(values []string, item string) []string {
	for _, existing := range values {
		if existing == item {
			return values
		}
	}
	return append(values, item)
}

func asResourceDescriptor(value any) (*annotationspb.ResourceDescriptor, error) {
	switch typed := value.(type) {
	case *annotationspb.ResourceDescriptor:
		return typed, nil
	case annotationspb.ResourceDescriptor:
		descriptor := typed
		return &descriptor, nil
	default:
		return nil, fmt.Errorf("unexpected resource extension type %T", value)
	}
}

func asResourceDescriptorList(value any) ([]*annotationspb.ResourceDescriptor, error) {
	switch typed := value.(type) {
	case []*annotationspb.ResourceDescriptor:
		return typed, nil
	case *[]*annotationspb.ResourceDescriptor:
		if typed == nil {
			return nil, nil
		}
		return *typed, nil
	case []annotationspb.ResourceDescriptor:
		out := make([]*annotationspb.ResourceDescriptor, 0, len(typed))
		for i := range typed {
			descriptor := typed[i]
			out = append(out, &descriptor)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("unexpected resource_definition extension type %T", value)
	}
}

func asResourceReference(value any) (*annotationspb.ResourceReference, error) {
	switch typed := value.(type) {
	case *annotationspb.ResourceReference:
		return typed, nil
	case annotationspb.ResourceReference:
		reference := typed
		return &reference, nil
	default:
		return nil, fmt.Errorf("unexpected resource_reference extension type %T", value)
	}
}

func (annotations fileAnnotations) hasContent() bool {
	return len(annotations.messageResources) > 0 ||
		len(annotations.messages) > 0 ||
		len(annotations.services) > 0
}

func generateFileContent(g *protogen.GeneratedFile, annotations fileAnnotations) {
	if len(annotations.messageResources) > 0 {
		generateResourcePatternConstants(g, annotations.messageResources)
		generateResourceDescriptors(g, annotations.messageResources)
		generateMessageResourceMethods(g, annotations.messageResources)
	}

	if len(annotations.messages) > 0 {
		generateMessageMetadataMethods(g, annotations.messages)
	}

	if len(annotations.services) > 0 {
		generateServiceMetadataFunctions(g, annotations.services)
	}
}

func generateResourcePatternConstants(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		if len(resource.patterns) == 1 {
			g.P("const ", messageResourcePatternConstName(resource, 0), " = ", strconv.Quote(resource.patterns[0]))
			g.P()
			continue
		}

		g.P("const (")
		for i, pattern := range resource.patterns {
			g.P("\t", messageResourcePatternConstName(resource, i), " = ", strconv.Quote(pattern))
		}
		g.P(")")
		g.P()
	}
}

func generateResourceDescriptors(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		g.P("var ", messageResourceVarName(resource), " = ", runtime(g, "ResourceDescriptor"), "{")
		writeResourceDescriptorFields(g, resource)
		g.P("}")
		g.P()
	}
	g.P()
}

func generateMessageResourceMethods(g *protogen.GeneratedFile, resources []messageResource) {
	for _, resource := range resources {
		varName := messageResourceVarName(resource)
		fieldExpr := "x." + resource.nameFieldGoName
		nilReceiverError := strconv.Quote("nil *" + resource.goName + " receiver")

		g.P(
			"func (x *", resource.goName, ") ParseName() (",
			runtime(g, "ResourceMatch"),
			", error) {",
		)
		g.P("\tif x == nil {")
		g.P("\t\treturn ", runtime(g, "ResourceMatch"), "{}, ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\treturn ", varName, ".Parse(", fieldExpr, ")")
		g.P("}")
		g.P()

		g.P("func (x *", resource.goName, ") ValidateName() error {")
		g.P("\tif x == nil {")
		g.P("\t\treturn ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\treturn ", varName, ".Validate(", fieldExpr, ")")
		g.P("}")
		g.P()

		g.P(
			"func (x *", resource.goName, ") FillNameWithPattern(pattern string, values map[string]string) error {",
		)
		g.P("\tif x == nil {")
		g.P("\t\treturn ", stdfmt(g, "Errorf"), "(", nilReceiverError, ")")
		g.P("\t}")
		g.P("\tformatted, err := ", varName, ".FormatWithPattern(pattern, values)")
		g.P("\tif err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
		g.P("\t", fieldExpr, " = formatted")
		g.P("\treturn nil")
		g.P("}")
		g.P()

		if len(resource.patterns) == 1 {
			g.P("func (x *", resource.goName, ") FillName(values map[string]string) error {")
			g.P("\treturn x.FillNameWithPattern(", messageResourcePatternConstName(resource, 0), ", values)")
			g.P("}")
			g.P()
		}
	}
}

func generateMessageMetadataMethods(g *protogen.GeneratedFile, messages []messageMetadata) {
	for _, message := range messages {
		if len(message.resourceRefs) > 0 {
			resourceVarName := messageResourceReferenceVarName(message)
			g.P("var ", resourceVarName, " = map[string]", runtime(g, "ResourceReferenceMetadata"), "{")
			for _, fieldName := range sortedNestedKeysSingle(message.resourceRefs) {
				ref := message.resourceRefs[fieldName]
				g.P(strconv.Quote(fieldName), ": ", runtime(g, "ResourceReferenceMetadata"), "{")
				g.P("Type: ", strconv.Quote(ref.resourceType), ",")
				g.P("ChildType: ", strconv.Quote(ref.childType), ",")
				g.P("MessageFullName: ", strconv.Quote(ref.messageFullName), ",")
				g.P("FieldName: ", strconv.Quote(ref.fieldName), ",")
				g.P("},")
			}
			g.P("}")
			g.P()

			g.P(
				"func (", message.goName, ") GoogleAIPResourceReference(fieldName string) (",
				runtime(g, "ResourceReferenceMetadata"),
				", bool) {",
			)
			g.P("\treference, ok := ", resourceVarName, "[fieldName]")
			g.P("\tif !ok {")
			g.P("\t\treturn ", runtime(g, "ResourceReferenceMetadata"), "{}, false")
			g.P("\t}")
			g.P("\treturn reference, true")
			g.P("}")
			g.P()
		}

		if len(message.fieldBehaviors) > 0 {
			fieldBehaviorVarName := messageFieldBehaviorVarName(message)
			g.P("var ", fieldBehaviorVarName, " = map[string][]", ann(g, "FieldBehavior"), "{")
			for _, fieldName := range sortedNestedKeysSingle(message.fieldBehaviors) {
				g.P(strconv.Quote(fieldName), ": {")
				for _, behavior := range message.fieldBehaviors[fieldName] {
					g.P(ann(g, "FieldBehavior"), "(", strconv.Itoa(int(behavior)), "),")
				}
				g.P("},")
			}
			g.P("}")
			g.P()
		}

		if len(message.fieldBehaviors) > 0 || len(message.requiredFields) > 0 {
			g.P("func (", message.goName, ") GoogleAIPFieldBehaviors(fieldName string) []", ann(g, "FieldBehavior"), " {")
			if len(message.fieldBehaviors) == 0 {
				g.P("\treturn nil")
			} else {
				g.P("\tbehaviors, ok := ", messageFieldBehaviorVarName(message), "[fieldName]")
				g.P("\tif !ok {")
				g.P("\t\treturn nil")
				g.P("\t}")
				g.P("\treturn append([]", ann(g, "FieldBehavior"), "(nil), behaviors...)")
			}
			g.P("}")
			g.P()

			if len(message.requiredFields) > 0 {
				requiredFieldsVarName := messageRequiredFieldsVarName(message)
				g.P("var ", requiredFieldsVarName, " = []string{")
				for _, fieldName := range message.requiredFields {
					g.P(strconv.Quote(fieldName), ",")
				}
				g.P("}")
				g.P()

				g.P("func (", message.goName, ") GoogleAIPRequiredFields() []string {")
				g.P("\treturn append([]string(nil), ", requiredFieldsVarName, "...)")
				g.P("}")
				g.P()
				continue
			}

			g.P("func (", message.goName, ") GoogleAIPRequiredFields() []string {")
			g.P("\treturn nil")
			g.P("}")
			g.P()
		}
	}
}

func generateServiceMetadataFunctions(g *protogen.GeneratedFile, services []serviceMetadata) {
	for _, service := range services {
		methodSignaturesVarName := serviceMethodSignatureVarName(service)
		g.P("var ", methodSignaturesVarName, " = map[string][][]string{")
		for _, methodName := range sortedNestedKeysSingle(service.methodSignatures) {
			g.P(strconv.Quote(methodName), ": {")
			for _, signature := range service.methodSignatures[methodName] {
				g.P("{")
				for _, fieldName := range signature {
					g.P(strconv.Quote(fieldName), ",")
				}
				g.P("},")
			}
			g.P("},")
		}
		g.P("}")
		g.P()

		g.P("func ", service.goName, "GoogleAIPMethodSignatures(methodName string) [][]string {")
		g.P("\tsignatures, ok := ", methodSignaturesVarName, "[methodName]")
		g.P("\tif !ok {")
		g.P("\t\treturn nil")
		g.P("\t}")
		g.P("\tout := make([][]string, 0, len(signatures))")
		g.P("\tfor _, signature := range signatures {")
		g.P("\t\tout = append(out, append([]string(nil), signature...))")
		g.P("\t}")
		g.P("\treturn out")
		g.P("}")
		g.P()
	}
}

func messageResourceVarName(resource messageResource) string {
	return "googleAIPResource" + resource.goName + "Descriptor"
}

func messageResourcePatternConstName(resource messageResource, index int) string {
	base := resource.goName + "NamePattern"
	if len(resource.patterns) == 1 {
		return base
	}
	return base + strconv.Itoa(index+1)
}

func messageResourceReferenceVarName(message messageMetadata) string {
	return "googleAIP" + message.goName + "ResourceReferences"
}

func messageFieldBehaviorVarName(message messageMetadata) string {
	return "googleAIP" + message.goName + "FieldBehaviors"
}

func messageRequiredFieldsVarName(message messageMetadata) string {
	return "googleAIP" + message.goName + "RequiredFields"
}

func serviceMethodSignatureVarName(service serviceMetadata) string {
	return "googleAIP" + service.goName + "MethodSignatures"
}

func writeResourceDescriptorFields(g *protogen.GeneratedFile, resource messageResource) {
	g.P("Type: ", strconv.Quote(resource.resourceType), ",")
	g.P("Plural: ", strconv.Quote(resource.plural), ",")
	g.P("Singular: ", strconv.Quote(resource.singular), ",")
	g.P("NameField: ", strconv.Quote(resource.nameField), ",")
	g.P("Patterns: []", runtime(g, "ResourcePattern"), "{")
	for i := range resource.patterns {
		g.P(runtime(g, "MustCompilePattern"), "(", messageResourcePatternConstName(resource, i), "),")
	}
	g.P("},")
}

func sortedNestedKeysSingle[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func runtime(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(runtimePackage.Ident(name))
}

func ann(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(annotationsPackage.Ident(name))
}

func stdfmt(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(fmtPackage.Ident(name))
}
