CREATE TABLE xevent_outbox_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  message_id VARCHAR(36) NOT NULL DEFAULT '',
  mode VARCHAR(16) NOT NULL,
  handoff_from_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(255) NOT NULL,
  event_id VARCHAR(255) NOT NULL DEFAULT '',
  partition_key VARCHAR(255) NOT NULL DEFAULT '',
  payload LONGBLOB NOT NULL,
  topic VARCHAR(255) NOT NULL DEFAULT '',
  available_at DATETIME(6) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT '',
  attempts INT NOT NULL DEFAULT 0,
  last_error LONGTEXT NULL,
  claim_owner VARCHAR(255) NOT NULL DEFAULT '',
  claim_until DATETIME(6) NULL,
  sent_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY idx_xevent_outbox_handoff_from_id (handoff_from_id),
  KEY idx_xevent_outbox_mode_status_partition_available_id (mode, status, partition_key, available_at, id),
  KEY idx_xevent_outbox_mode_created_at (mode, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
