// Code generated by protoc-gen-codesjoy-ddd. DO NOT EDIT.
// source: codesjoy/example/order/v1/order.proto

package orderv1

import (
	context "context"
	xevent "github.com/codesjoy/pkg/basic/xevent"
	proto "google.golang.org/protobuf/proto"
)

var _ xevent.Event = (*AuditPing)(nil)

func (*AuditPing) EventType() string {
	return "audit.ping"
}

func (x *AuditPing) EventID() string {
	return ""
}

func (x *AuditPing) PartitionKey() string {
	return ""
}

func (x *AuditPing) MarshalPayload() ([]byte, error) {
	return proto.Marshal(x)
}

func (x *AuditPing) UnmarshalPayload(data []byte) error {
	return proto.Unmarshal(data, x)
}

func OnAuditPing(
	d *xevent.Dispatcher,
	handlers ...func(context.Context, *AuditPing) error,
) error {
	if len(handlers) == 0 {
		return xevent.ErrInvalidEventBinding
	}
	for _, handler := range handlers {
		if err := xevent.On[*AuditPing](d, handler); err != nil {
			return err
		}
	}
	return nil
}

var _ xevent.Event = (*OrderCreated)(nil)

func (*OrderCreated) EventType() string {
	return "codesjoy.example.order.v1.OrderCreated"
}

func (x *OrderCreated) EventID() string {
	if x == nil {
		return ""
	}
	return x.GetId()
}

func (x *OrderCreated) PartitionKey() string {
	if x == nil {
		return ""
	}
	return x.GetOrderId()
}

func (x *OrderCreated) MarshalPayload() ([]byte, error) {
	return proto.Marshal(x)
}

func (x *OrderCreated) UnmarshalPayload(data []byte) error {
	return proto.Unmarshal(data, x)
}

func OnOrderCreated(
	d *xevent.Dispatcher,
	handlers ...func(context.Context, *OrderCreated) error,
) error {
	if len(handlers) == 0 {
		return xevent.ErrInvalidEventBinding
	}
	for _, handler := range handlers {
		if err := xevent.On[*OrderCreated](d, handler); err != nil {
			return err
		}
	}
	return nil
}
