// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codesjoy/example/user/v1/reason.proto

package userv1

import (
	_ "github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason/proto/codesjoy/reason/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReason int32

const (
	UserReason_USER_REASON_UNSPECIFIED UserReason = 0
	UserReason_USER_REASON_NOT_FOUND   UserReason = 5000
	UserReason_USER_REASON_BLOCKED     UserReason = 5001
	UserReason_USER_REASON_STORAGE     UserReason = 5002
)

// Enum value maps for UserReason.
var (
	UserReason_name = map[int32]string{
		0:    "USER_REASON_UNSPECIFIED",
		5000: "USER_REASON_NOT_FOUND",
		5001: "USER_REASON_BLOCKED",
		5002: "USER_REASON_STORAGE",
	}
	UserReason_value = map[string]int32{
		"USER_REASON_UNSPECIFIED": 0,
		"USER_REASON_NOT_FOUND":   5000,
		"USER_REASON_BLOCKED":     5001,
		"USER_REASON_STORAGE":     5002,
	}
)

func (x UserReason) Enum() *UserReason {
	p := new(UserReason)
	*p = x
	return p
}

func (x UserReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserReason) Descriptor() protoreflect.EnumDescriptor {
	return file_codesjoy_example_user_v1_reason_proto_enumTypes[0].Descriptor()
}

func (UserReason) Type() protoreflect.EnumType {
	return &file_codesjoy_example_user_v1_reason_proto_enumTypes[0]
}

func (x UserReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserReason.Descriptor instead.
func (UserReason) EnumDescriptor() ([]byte, []int) {
	return file_codesjoy_example_user_v1_reason_proto_rawDescGZIP(), []int{0}
}

var File_codesjoy_example_user_v1_reason_proto protoreflect.FileDescriptor

const file_codesjoy_example_user_v1_reason_proto_rawDesc = "" +
	"\n" +
	"%codesjoy/example/user/v1/reason.proto\x12\x18codesjoy.example.user.v1\x1a\x1fcodesjoy/reason/v1/reason.proto*\x93\x01\n" +
	"\n" +
	"UserReason\x12 \n" +
	"\x17USER_REASON_UNSPECIFIED\x10\x00\x1a\x03\xa8E\x00\x12\x1f\n" +
	"\x15USER_REASON_NOT_FOUND\x10\x88'\x1a\x03\xa8E\x05\x12\x1d\n" +
	"\x13USER_REASON_BLOCKED\x10\x89'\x1a\x03\xa8E\a\x12\x1d\n" +
	"\x13USER_REASON_STORAGE\x10\x8a'\x1a\x03\xa8E\r\x1a\x04\xa0E\x88'BkZigithub.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason/example/protogen/codesjoy/example/user/v1;userv1b\x06proto3"

var (
	file_codesjoy_example_user_v1_reason_proto_rawDescOnce sync.Once
	file_codesjoy_example_user_v1_reason_proto_rawDescData []byte
)

func file_codesjoy_example_user_v1_reason_proto_rawDescGZIP() []byte {
	file_codesjoy_example_user_v1_reason_proto_rawDescOnce.Do(func() {
		file_codesjoy_example_user_v1_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codesjoy_example_user_v1_reason_proto_rawDesc), len(file_codesjoy_example_user_v1_reason_proto_rawDesc)))
	})
	return file_codesjoy_example_user_v1_reason_proto_rawDescData
}

var file_codesjoy_example_user_v1_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codesjoy_example_user_v1_reason_proto_goTypes = []any{
	(UserReason)(0), // 0: codesjoy.example.user.v1.UserReason
}
var file_codesjoy_example_user_v1_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codesjoy_example_user_v1_reason_proto_init() }
func file_codesjoy_example_user_v1_reason_proto_init() {
	if File_codesjoy_example_user_v1_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codesjoy_example_user_v1_reason_proto_rawDesc), len(file_codesjoy_example_user_v1_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codesjoy_example_user_v1_reason_proto_goTypes,
		DependencyIndexes: file_codesjoy_example_user_v1_reason_proto_depIdxs,
		EnumInfos:         file_codesjoy_example_user_v1_reason_proto_enumTypes,
	}.Build()
	File_codesjoy_example_user_v1_reason_proto = out.File
	file_codesjoy_example_user_v1_reason_proto_goTypes = nil
	file_codesjoy_example_user_v1_reason_proto_depIdxs = nil
}
