// Code generated by protoc-gen-codesjoy-reason. DO NOT EDIT.

package userv1

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the reason plugin package it is being compiled against.

var UserReason_code = map[int32]code.Code{
	0:    code.Code_OK,
	5000: code.Code_NOT_FOUND,
	5001: code.Code_PERMISSION_DENIED,
	5002: code.Code_INTERNAL,
}

func (r UserReason) Reason() string {
	return UserReason_name[int32(r)]
}

func (r UserReason) Domain() string {
	return "codesjoy.example.user.v1"
}

func (r UserReason) Code() code.Code {
	return UserReason_code[int32(r)]
}
