// Code generated by codesjoy-modelgen. DO NOT EDIT.

package demo

import (
	aipsql "github.com/codesjoy/pkg/basic/aipsql"
	soft_delete "gorm.io/plugin/soft_delete"
)

// User is a generated GORM model for table "users".
type User struct {
	ID        int64                 `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
	Name      string                `gorm:"column:name" json:"name"`
	IsActive  bool                  `gorm:"column:is_active" json:"is_active"`
	CreatedAt int64                 `gorm:"column:created_at;autoCreateTime:nano" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:update;autoUpdateTime:nano" json:"update"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;softDelete:nano" json:"deleted_at"`
}

// TableName returns the database table name for User.
func (User) TableName() string {
	return "users"
}

// AIPTable builds the aipsql.Table mapped to "users".
func (User) AIPTable() *aipsql.Table {
	table := aipsql.NewTable().WithColumns(
		aipsql.NewColumn().
			WithFieldPath("id").
			WithDatabaseName("id").
			Filterable().
			Sortable().
			Build(),
		aipsql.NewColumn().
			WithFieldPath("name").
			WithDatabaseName("name").
			Filterable().
			WithMatchModes(aipsql.MatchModeExact, aipsql.MatchModePrefix).
			Build(),
		aipsql.NewColumn().
			WithFieldPath("is_active").
			WithDatabaseName("is_active").
			Bool().
			Filterable().
			Sortable().
			Build(),
		aipsql.NewColumn().
			WithFieldPath("created_at").
			WithDatabaseName("created_at").
			Filterable().
			Sortable().
			Build(),
		aipsql.NewColumn().
			WithFieldPath("update").
			WithDatabaseName("update").
			Filterable().
			Build(),
		aipsql.NewColumn().
			WithFieldPath("deleted_at").
			WithDatabaseName("deleted_at").
			Filterable().
			Sortable().
			Build(),
	).Build()
	table.CompositeIndexes = []aipsql.CompositeIndex{
		{
			Name:    "idx_users_created_id",
			Columns: []string{"created_at", "id"},
		},
	}
	return table
}

// NewUserAIPTable keeps compatibility with package-level AIP table builders.
func NewUserAIPTable() *aipsql.Table {
	return User{}.AIPTable()
}
