style: github
template: .chglog/CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/codesjoy/pkg
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - perf
        - revert
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Refactors
      perf: Performance Improvements
      revert: Reverts
  header:
    pattern: "^([[:alnum:]]+)(?:\\(([[:alnum:]_./\\-\\s]+)\\))?(!)?:\\s(.+)$"
    pattern_maps:
      - Type
      - Scope
      - Breaking
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
