// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"
	"testing"

	eventv1 "github.com/codesjoy/pkg/proto/codesjoy/ddd/event/v1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestGenerateFilesEnabledMessageUsesFullNameByDefault(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Messages[0].Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(file.Messages[0].Fields[0].Desc.Options(), eventv1.E_EventId, true)
	proto.SetExtension(file.Messages[0].Fields[1].Desc.Options(), eventv1.E_PartitionKey, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "order_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, "// Code generated by protoc-gen-codesjoy-event. DO NOT EDIT.")
	assert.Contains(t, content, "var _ xevent.Event = (*OrderCreated)(nil)")
	assert.Contains(t, content, `func (*OrderCreated) EventType() string {`)
	assert.Contains(t, content, `return "codesjoy.example.order.v1.OrderCreated"`)
	assert.Contains(t, content, "return x.GetId()")
	assert.Contains(t, content, "return x.GetOrderId()")
	assert.Contains(t, content, `func (*OrderCreated) Topic() string {`)
	assert.Contains(t, content, "return proto.Marshal(x)")
	assert.Contains(t, content, "return proto.Unmarshal(data, x)")
	assert.Contains(t, content, `func OnOrderCreated(`)
	assert.Contains(t, content, `handlers ...func(context.Context, *OrderCreated) error`)
	assert.Contains(t, content, `return xevent.ErrInvalidEventBinding`)
	assert.Contains(t, content, `xevent.On[*OrderCreated](d, handler)`)
}

func TestGenerateFilesExplicitEventTypeOverride(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	message := gen.Files[0].Messages[1]
	proto.SetExtension(message.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{
		EventType: "order.deleted",
	})
	proto.SetExtension(message.Fields[0].Desc.Options(), eventv1.E_EventId, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "order_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, `func (*OrderDeleted) EventType() string {`)
	assert.Contains(t, content, `return "order.deleted"`)
}

func TestGenerateFilesSameFileMultipleMessages(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	file := gen.Files[0]
	orderCreated := file.Messages[0]
	orderDeleted := file.Messages[1]

	proto.SetExtension(orderCreated.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(orderCreated.Fields[0].Desc.Options(), eventv1.E_EventId, true)
	proto.SetExtension(orderDeleted.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{
		EventType: "order.deleted",
	})
	proto.SetExtension(orderDeleted.Fields[0].Desc.Options(), eventv1.E_EventId, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "order_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, "(*OrderCreated)(nil)")
	assert.Contains(t, content, "(*OrderDeleted)(nil)")
	assert.Contains(t, content, `return "codesjoy.example.order.v1.OrderCreated"`)
	assert.Contains(t, content, `return "order.deleted"`)
	assert.Contains(t, content, `func OnOrderCreated(`)
	assert.Contains(t, content, `func OnOrderDeleted(`)
}

func TestGenerateFilesSkipWhenNoAnnotations(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	require.NoError(t, generateFiles(gen))
	assert.Empty(t, generatedFileContent(gen, "order_codesjoy_event.pb.go"))
}

func TestGenerateFilesNestedMessageGeneratesAndSkipsMapEntry(t *testing.T) {
	gen, err := newTestPluginWithFiles(
		[]string{"nested.proto"},
		[]*descriptorpb.FileDescriptorProto{
			newNestedFile(),
		},
	)
	require.NoError(t, err)

	envelope := gen.Files[0].Messages[0]
	inner := envelope.Messages[0]
	proto.SetExtension(inner.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(inner.Fields[0].Desc.Options(), eventv1.E_EventId, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "nested_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, `return "codesjoy.example.order.v1.Envelope.OrderCreated"`)
	assert.Contains(t, content, `func OnEnvelope_OrderCreated(`)
	assert.NotContains(t, content, "TagsEntry")
}

func TestGenerateFilesDuplicateEventIDErrors(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	message := gen.Files[0].Messages[0]
	proto.SetExtension(message.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(message.Fields[0].Desc.Options(), eventv1.E_EventId, true)
	proto.SetExtension(message.Fields[1].Desc.Options(), eventv1.E_EventId, true)

	err = generateFiles(gen)
	require.Error(t, err)
	assert.Contains(
		t,
		err.Error(),
		"file order.proto: message codesjoy.example.order.v1.OrderCreated field order_id",
	)
	assert.Contains(t, err.Error(), "duplicate event_id annotation")
}

func TestGenerateFilesDuplicatePartitionKeyErrors(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	message := gen.Files[0].Messages[0]
	proto.SetExtension(message.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(message.Fields[0].Desc.Options(), eventv1.E_PartitionKey, true)
	proto.SetExtension(message.Fields[1].Desc.Options(), eventv1.E_PartitionKey, true)

	err = generateFiles(gen)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "duplicate partition_key annotation")
}

func TestGenerateFilesFieldAnnotationWithoutEventTypeErrors(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	proto.SetExtension(gen.Files[0].Messages[0].Fields[0].Desc.Options(), eventv1.E_EventId, true)

	err = generateFiles(gen)
	require.Error(t, err)
	assert.Contains(
		t,
		err.Error(),
		"field annotation requires message option (codesjoy.ddd.event.v1.event)",
	)
}

func TestGenerateFilesTopicOptionGeneratesTopicMethod(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	proto.SetExtension(gen.Files[0].Messages[0].Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{
		Topic: "orders",
	})
	proto.SetExtension(gen.Files[0].Messages[0].Fields[0].Desc.Options(), eventv1.E_EventId, true)
	proto.SetExtension(gen.Files[0].Messages[0].Fields[1].Desc.Options(), eventv1.E_PartitionKey, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "order_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, `func (*OrderCreated) Topic() string {`)
	assert.Contains(t, content, `return "orders"`)
}

func TestGenerateFilesNoTopicGeneratesEmptyTopicMethod(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	proto.SetExtension(gen.Files[0].Messages[0].Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
	proto.SetExtension(gen.Files[0].Messages[0].Fields[0].Desc.Options(), eventv1.E_EventId, true)

	require.NoError(t, generateFiles(gen))

	content := generatedFileContent(gen, "order_codesjoy_event.pb.go")
	require.NotEmpty(t, content)
	assert.Contains(t, content, `func (*OrderCreated) Topic() string {`)
	assert.Contains(t, content, `return ""`)
	assert.NotContains(t, content, "TopicResolver")
}

func TestGenerateFilesBlankEventTypeErrors(t *testing.T) {
	gen, err := newTestPluginWithFiles([]string{"order.proto"}, []*descriptorpb.FileDescriptorProto{
		newOrderFile(),
	})
	require.NoError(t, err)

	proto.SetExtension(
		gen.Files[0].Messages[0].Desc.Options(),
		eventv1.E_Event,
		&eventv1.EventOptions{
			EventType: " ",
		},
	)

	err = generateFiles(gen)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "event.event_type must not be blank")
}

func TestGenerateFilesInvalidAnnotatedFieldErrors(t *testing.T) {
	tests := []struct {
		name       string
		file       *descriptorpb.FileDescriptorProto
		fieldPath  []int
		wantSubstr string
	}{
		{
			name:       "non-string",
			file:       newInvalidTypeFile(),
			fieldPath:  []int{0, 0},
			wantSubstr: "annotation requires a string field",
		},
		{
			name:       "repeated",
			file:       newRepeatedFile(),
			fieldPath:  []int{0, 0},
			wantSubstr: "annotation requires a non-repeated string field",
		},
		{
			name:       "map",
			file:       newMapFile(),
			fieldPath:  []int{0, 0},
			wantSubstr: "annotation requires a non-map string field",
		},
		{
			name:       "oneof",
			file:       newOneofFile(),
			fieldPath:  []int{0, 0},
			wantSubstr: "annotation requires a non-oneof string field",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gen, err := newTestPluginWithFiles(
				[]string{tt.file.GetName()},
				[]*descriptorpb.FileDescriptorProto{
					tt.file,
				},
			)
			require.NoError(t, err)

			message := gen.Files[0].Messages[tt.fieldPath[0]]
			field := message.Fields[tt.fieldPath[1]]
			proto.SetExtension(message.Desc.Options(), eventv1.E_Event, &eventv1.EventOptions{})
			proto.SetExtension(field.Desc.Options(), eventv1.E_EventId, true)

			err = generateFiles(gen)
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.wantSubstr)
		})
	}
}

func newTestPluginWithFiles(
	filesToGenerate []string,
	files []*descriptorpb.FileDescriptorProto,
) (*protogen.Plugin, error) {
	return protogen.Options{}.New(&pluginpb.CodeGeneratorRequest{
		FileToGenerate: filesToGenerate,
		ProtoFile:      files,
	})
}

func generatedFileContent(gen *protogen.Plugin, suffix string) string {
	for _, file := range gen.Response().File {
		if strings.HasSuffix(file.GetName(), suffix) {
			return file.GetContent()
		}
	}
	return ""
}

func newOrderFile() *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String("order.proto"),
		Package: proto.String("codesjoy.example.order.v1"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1",
			),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			newMessage(
				"OrderCreated",
				[]*descriptorpb.FieldDescriptorProto{
					stringField("id", 1),
					stringField("order_id", 2),
					stringField("user_id", 3),
				},
			),
			newMessage(
				"OrderDeleted",
				[]*descriptorpb.FieldDescriptorProto{
					stringField("id", 1),
				},
			),
		},
	}
}

func newNestedFile() *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String("nested.proto"),
		Package: proto.String("codesjoy.example.order.v1"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1",
			),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: proto.String("Envelope"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:     proto.String("tags"),
						Number:   proto.Int32(1),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
						TypeName: proto.String(".codesjoy.example.order.v1.Envelope.TagsEntry"),
						Options:  &descriptorpb.FieldOptions{},
					},
				},
				NestedType: []*descriptorpb.DescriptorProto{
					newMessage("OrderCreated", []*descriptorpb.FieldDescriptorProto{
						stringField("id", 1),
					}),
					{
						Name: proto.String("TagsEntry"),
						Field: []*descriptorpb.FieldDescriptorProto{
							stringField("key", 1),
							stringField("value", 2),
						},
						Options: &descriptorpb.MessageOptions{
							MapEntry: proto.Bool(true),
						},
					},
				},
				Options: &descriptorpb.MessageOptions{},
			},
		},
	}
}

func newInvalidTypeFile() *descriptorpb.FileDescriptorProto {
	return singleMessageFile(
		"invalid_type.proto",
		newMessage("OrderCreated", []*descriptorpb.FieldDescriptorProto{
			int32Field("id", 1),
		}),
	)
}

func newRepeatedFile() *descriptorpb.FileDescriptorProto {
	return singleMessageFile(
		"repeated.proto",
		newMessage("OrderCreated", []*descriptorpb.FieldDescriptorProto{
			repeatedStringField("ids", 1),
		}),
	)
}

func newMapFile() *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String("map.proto"),
		Package: proto.String("codesjoy.example.order.v1"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1",
			),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: proto.String("OrderCreated"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:   proto.String("attrs"),
						Number: proto.Int32(1),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
						TypeName: proto.String(
							".codesjoy.example.order.v1.OrderCreated.AttrsEntry",
						),
						Options: &descriptorpb.FieldOptions{},
					},
				},
				NestedType: []*descriptorpb.DescriptorProto{
					{
						Name: proto.String("AttrsEntry"),
						Field: []*descriptorpb.FieldDescriptorProto{
							stringField("key", 1),
							stringField("value", 2),
						},
						Options: &descriptorpb.MessageOptions{
							MapEntry: proto.Bool(true),
						},
					},
				},
				Options: &descriptorpb.MessageOptions{},
			},
		},
	}
}

func newOneofFile() *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String("oneof.proto"),
		Package: proto.String("codesjoy.example.order.v1"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1",
			),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: proto.String("OrderCreated"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:       proto.String("id"),
						Number:     proto.Int32(1),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						OneofIndex: proto.Int32(0),
						Options:    &descriptorpb.FieldOptions{},
					},
				},
				OneofDecl: []*descriptorpb.OneofDescriptorProto{
					{Name: proto.String("event_ref")},
				},
				Options: &descriptorpb.MessageOptions{},
			},
		},
	}
}

func singleMessageFile(
	name string,
	message *descriptorpb.DescriptorProto,
) *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String(name),
		Package: proto.String("codesjoy.example.order.v1"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-event/example/protogen/codesjoy/example/order/v1;orderv1",
			),
		},
		MessageType: []*descriptorpb.DescriptorProto{message},
	}
}

func newMessage(
	name string,
	fields []*descriptorpb.FieldDescriptorProto,
) *descriptorpb.DescriptorProto {
	return &descriptorpb.DescriptorProto{
		Name:    proto.String(name),
		Field:   fields,
		Options: &descriptorpb.MessageOptions{},
	}
}

func stringField(name string, number int32) *descriptorpb.FieldDescriptorProto {
	return &descriptorpb.FieldDescriptorProto{
		Name:    proto.String(name),
		Number:  proto.Int32(number),
		Label:   descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
		Type:    descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
		Options: &descriptorpb.FieldOptions{},
	}
}

func repeatedStringField(name string, number int32) *descriptorpb.FieldDescriptorProto {
	return &descriptorpb.FieldDescriptorProto{
		Name:    proto.String(name),
		Number:  proto.Int32(number),
		Label:   descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
		Type:    descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
		Options: &descriptorpb.FieldOptions{},
	}
}

func int32Field(name string, number int32) *descriptorpb.FieldDescriptorProto {
	return &descriptorpb.FieldDescriptorProto{
		Name:    proto.String(name),
		Number:  proto.Int32(number),
		Label:   descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
		Type:    descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
		Options: &descriptorpb.FieldOptions{},
	}
}
