// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codesjoy/ddd/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_codesjoy_ddd_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_codesjoy_ddd_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_codesjoy_ddd_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventOptions) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventOptions) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var file_codesjoy_ddd_event_v1_event_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         1110,
		Name:          "codesjoy.ddd.event.v1.event",
		Tag:           "bytes,1110,opt,name=event",
		Filename:      "codesjoy/ddd/event/v1/event.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1111,
		Name:          "codesjoy.ddd.event.v1.event_id",
		Tag:           "varint,1111,opt,name=event_id",
		Filename:      "codesjoy/ddd/event/v1/event.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1112,
		Name:          "codesjoy.ddd.event.v1.partition_key",
		Tag:           "varint,1112,opt,name=partition_key",
		Filename:      "codesjoy/ddd/event/v1/event.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional codesjoy.ddd.event.v1.EventOptions event = 1110;
	E_Event = &file_codesjoy_ddd_event_v1_event_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool event_id = 1111;
	E_EventId = &file_codesjoy_ddd_event_v1_event_proto_extTypes[1]
	// optional bool partition_key = 1112;
	E_PartitionKey = &file_codesjoy_ddd_event_v1_event_proto_extTypes[2]
)

var File_codesjoy_ddd_event_v1_event_proto protoreflect.FileDescriptor

const file_codesjoy_ddd_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"!codesjoy/ddd/event/v1/event.proto\x12\x15codesjoy.ddd.event.v1\x1a google/protobuf/descriptor.proto\"C\n" +
	"\fEventOptions\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic:[\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18\xd6\b \x01(\v2#.codesjoy.ddd.event.v1.EventOptionsR\x05event:9\n" +
	"\bevent_id\x12\x1d.google.protobuf.FieldOptions\x18\xd7\b \x01(\bR\aeventId:C\n" +
	"\rpartition_key\x12\x1d.google.protobuf.FieldOptions\x18\xd8\b \x01(\bR\fpartitionKeyB\xdb\x01\n" +
	"\x19com.codesjoy.ddd.event.v1B\n" +
	"EventProtoP\x01Z;github.com/codesjoy/pkg/proto/codesjoy/ddd/event/v1;eventv1\xa2\x02\x03CDE\xaa\x02\x15Codesjoy.Ddd.Event.V1\xca\x02\x15Codesjoy\\Ddd\\Event\\V1\xe2\x02!Codesjoy\\Ddd\\Event\\V1\\GPBMetadata\xea\x02\x18Codesjoy::Ddd::Event::V1b\x06proto3"

var (
	file_codesjoy_ddd_event_v1_event_proto_rawDescOnce sync.Once
	file_codesjoy_ddd_event_v1_event_proto_rawDescData []byte
)

func file_codesjoy_ddd_event_v1_event_proto_rawDescGZIP() []byte {
	file_codesjoy_ddd_event_v1_event_proto_rawDescOnce.Do(func() {
		file_codesjoy_ddd_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codesjoy_ddd_event_v1_event_proto_rawDesc), len(file_codesjoy_ddd_event_v1_event_proto_rawDesc)))
	})
	return file_codesjoy_ddd_event_v1_event_proto_rawDescData
}

var file_codesjoy_ddd_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_codesjoy_ddd_event_v1_event_proto_goTypes = []any{
	(*EventOptions)(nil),                // 0: codesjoy.ddd.event.v1.EventOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
}
var file_codesjoy_ddd_event_v1_event_proto_depIdxs = []int32{
	1, // 0: codesjoy.ddd.event.v1.event:extendee -> google.protobuf.MessageOptions
	2, // 1: codesjoy.ddd.event.v1.event_id:extendee -> google.protobuf.FieldOptions
	2, // 2: codesjoy.ddd.event.v1.partition_key:extendee -> google.protobuf.FieldOptions
	0, // 3: codesjoy.ddd.event.v1.event:type_name -> codesjoy.ddd.event.v1.EventOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codesjoy_ddd_event_v1_event_proto_init() }
func file_codesjoy_ddd_event_v1_event_proto_init() {
	if File_codesjoy_ddd_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codesjoy_ddd_event_v1_event_proto_rawDesc), len(file_codesjoy_ddd_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_codesjoy_ddd_event_v1_event_proto_goTypes,
		DependencyIndexes: file_codesjoy_ddd_event_v1_event_proto_depIdxs,
		MessageInfos:      file_codesjoy_ddd_event_v1_event_proto_msgTypes,
		ExtensionInfos:    file_codesjoy_ddd_event_v1_event_proto_extTypes,
	}.Build()
	File_codesjoy_ddd_event_v1_event_proto = out.File
	file_codesjoy_ddd_event_v1_event_proto_goTypes = nil
	file_codesjoy_ddd_event_v1_event_proto_depIdxs = nil
}
