// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"

	reasonv1 "github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason/proto/codesjoy/reason/v1"
	"google.golang.org/genproto/googleapis/rpc/code"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const codePackage = protogen.GoImportPath("google.golang.org/genproto/googleapis/rpc/code")

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + "_reason.pb.go"

	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	generateHeader(g, file)
	return generateFileContent(file, g)
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-codesjoy-reason. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func generateFileContent(file *protogen.File, g *protogen.GeneratedFile) error {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the reason plugin package it is being compiled against.")
	g.P()

	reasons := &Reasons{
		Domain:      string(file.Desc.Package()),
		CodePackage: g.QualifiedGoIdent(codePackage.Ident("")),
	}
	if err := collectReasons(file.Enums, reasons); err != nil {
		return err
	}
	if len(reasons.Reason) == 0 {
		g.Skip()
		return nil
	}

	rendered, err := reasons.execute()
	if err != nil {
		return err
	}
	g.P(rendered)
	return nil
}

func collectReasons(enums []*protogen.Enum, reasons *Reasons) error {
	for _, enum := range enums {
		if err := genReason(enum, reasons); err != nil {
			return err
		}
	}
	return nil
}

func genReason(enum *protogen.Enum, reasons *Reasons) error {
	if !proto.HasExtension(enum.Desc.Options(), reasonv1.E_DefaultReason) {
		return nil
	}

	wrapper := ReasonWrapper{
		Name:  string(enum.Desc.Name()),
		Codes: make([]ReasonCode, 0, len(enum.Values)),
	}
	for _, value := range enum.Values {
		errCode, err := enumValueCode(value)
		if err != nil {
			return fmt.Errorf("enum %s value %s: %w", enum.Desc.Name(), value.Desc.Name(), err)
		}
		wrapper.Codes = append(wrapper.Codes, ReasonCode{
			Number: int32(value.Desc.Number()),
			Code:   errCode,
		})
	}

	reasons.Reason = append(reasons.Reason, wrapper)
	return nil
}

func enumValueCode(value *protogen.EnumValue) (code.Code, error) {
	if !proto.HasExtension(value.Desc.Options(), reasonv1.E_Code) {
		return code.Code_UNKNOWN, nil
	}

	ext := proto.GetExtension(value.Desc.Options(), reasonv1.E_Code)
	switch typed := ext.(type) {
	case code.Code:
		return typed, nil
	case *code.Code:
		if typed == nil {
			return code.Code_UNKNOWN, nil
		}
		return *typed, nil
	case int32:
		return code.Code(typed), nil
	default:
		return code.Code_UNKNOWN, fmt.Errorf("unexpected code extension type %T", ext)
	}
}
