// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"
	"testing"

	reasonv1 "github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason/proto/codesjoy/reason/v1"
	"github.com/stretchr/testify/assert"
	"google.golang.org/genproto/googleapis/rpc/code"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestReasonsExecute(t *testing.T) {
	reasons := &Reasons{
		Domain:      "test.package",
		CodePackage: "code.",
		Reason: []ReasonWrapper{
			{
				Name: "ErrorReason",
				Codes: []ReasonCode{
					{Number: 0, Code: code.Code_OK},
					{Number: 1, Code: code.Code_CANCELLED},
				},
			},
		},
	}

	output, err := reasons.execute()
	assert.NoError(t, err)

	expected := `var ErrorReason_code = map[int32]code.Code{
	0: code.Code_OK,
	1: code.Code_CANCELLED,
}

func (r ErrorReason) Reason() string {
	return ErrorReason_name[int32(r)]
}

func (r ErrorReason) Domain() string {
	return "test.package"
}

func (r ErrorReason) Code() code.Code {
	return ErrorReason_code[int32(r)]
}`

	assert.Equal(t, expected, output)
}

func TestGenerateFile(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))
	proto.SetExtension(file.Enums[0].Values[0].Desc.Options(), reasonv1.E_Code, code.Code_OK)

	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.NotEmpty(t, content)
	assert.Contains(t, content, "// Code generated by protoc-gen-codesjoy-reason. DO NOT EDIT.")
	assert.Contains(t, content, "func (r ErrorReason) Reason() string")
	assert.Contains(t, content, "0: code.Code_OK,")
}

func TestGenerateFile_MissingCodeFallsBackUnknown(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))

	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.NotEmpty(t, content)
	assert.Contains(t, content, "0: code.Code_UNKNOWN,")
}

func TestGenerateFile_SkipWhenNoDefaultReason(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.Empty(t, content)
}

func newTestPlugin() (*protogen.Plugin, error) {
	return protogen.Options{}.New(&pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{
			{
				Name:    proto.String("test.proto"),
				Package: proto.String("codesjoy.reason.v1.test"),
				Options: &descriptorpb.FileOptions{
					GoPackage: proto.String(
						"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason;main",
					),
				},
				EnumType: []*descriptorpb.EnumDescriptorProto{
					{
						Name: proto.String("ErrorReason"),
						Value: []*descriptorpb.EnumValueDescriptorProto{
							{
								Name:    proto.String("OK"),
								Number:  proto.Int32(0),
								Options: &descriptorpb.EnumValueOptions{},
							},
						},
						Options: &descriptorpb.EnumOptions{},
					},
				},
			},
		},
	})
}

func generatedFileContent(gen *protogen.Plugin, suffix string) string {
	for _, file := range gen.Response().File {
		if strings.HasSuffix(file.GetName(), suffix) {
			return file.GetContent()
		}
	}
	return ""
}
