// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"
	"testing"

	reasonv1 "github.com/codesjoy/pkg/proto/codesjoy/reason/v1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/genproto/googleapis/rpc/code"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestReasonsExecute(t *testing.T) {
	reasons := &Reasons{
		Domain:      "test.package",
		CodePackage: "code.",
		Reason: []ReasonWrapper{
			{
				Name: "ErrorReason",
				Codes: []ReasonCode{
					{Number: 0, Code: code.Code_OK},
					{Number: 1, Code: code.Code_CANCELLED},
				},
			},
		},
	}

	output, err := reasons.execute()
	assert.NoError(t, err)

	expected := `var ErrorReason_code = map[int32]code.Code{
	0: code.Code_OK,
	1: code.Code_CANCELLED,
}

func (r ErrorReason) Reason() string {
	return ErrorReason_name[int32(r)]
}

func (r ErrorReason) Domain() string {
	return "test.package"
}

func (r ErrorReason) Code() code.Code {
	return ErrorReason_code[int32(r)]
}`

	assert.Equal(t, expected, output)
}

func TestGenerateFile(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))
	proto.SetExtension(file.Enums[0].Values[0].Desc.Options(), reasonv1.E_Code, code.Code_OK)

	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.NotEmpty(t, content)
	assert.Contains(t, content, "// Code generated by protoc-gen-codesjoy-reason. DO NOT EDIT.")
	assert.Contains(t, content, "func (r ErrorReason) Reason() string")
	assert.Contains(t, content, "0: code.Code_OK,")
}

func TestGenerateFile_MissingCodeFallsBackUnknown(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))

	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.NotEmpty(t, content)
	assert.Contains(t, content, "0: code.Code_UNKNOWN,")
}

func TestGenerateFile_SkipWhenNoDefaultReason(t *testing.T) {
	gen, err := newTestPlugin()
	assert.NoError(t, err)

	file := gen.Files[0]
	err = generateFile(gen, file)
	assert.NoError(t, err)

	content := generatedFileContent(gen, "test_reason.pb.go")
	assert.Empty(t, content)
}

func TestReasonsExecute_InvalidTemplate(t *testing.T) {
	oldTpl := tpl
	tpl = "{{"
	defer func() { tpl = oldTpl }()

	_, err := (&Reasons{}).execute()
	require.Error(t, err)
}

func TestGenerateFiles(t *testing.T) {
	t.Run("skips files marked as not generated", func(t *testing.T) {
		gen, err := newTestPlugin()
		require.NoError(t, err)

		file := gen.Files[0]
		proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))
		proto.SetExtension(file.Enums[0].Values[0].Desc.Options(), reasonv1.E_Code, code.Code_OK)
		file.Generate = false

		require.NoError(t, generateFiles(gen))
		assert.Empty(t, generatedFileContent(gen, "test_reason.pb.go"))
	})

	t.Run("returns first generation error", func(t *testing.T) {
		gen, err := newTestPlugin()
		require.NoError(t, err)

		proto.SetExtension(gen.Files[0].Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))

		oldTpl := tpl
		tpl = "{{"
		defer func() { tpl = oldTpl }()

		require.Error(t, generateFiles(gen))
	})
}

func TestCollectReasons(t *testing.T) {
	gen, err := newTestPluginWithFiles(
		[]string{"test.proto"},
		[]*descriptorpb.FileDescriptorProto{
			{
				Name:    proto.String("test.proto"),
				Package: proto.String("codesjoy.reason.v1.test"),
				Options: &descriptorpb.FileOptions{
					GoPackage: proto.String(
						"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason;main",
					),
				},
				EnumType: []*descriptorpb.EnumDescriptorProto{
					newReasonEnum("ErrorReason"),
					newReasonEnumWithValue("IgnoredReason", "IGNORED"),
				},
			},
		},
	)
	require.NoError(t, err)

	file := gen.Files[0]
	proto.SetExtension(file.Enums[0].Desc.Options(), reasonv1.E_DefaultReason, int32(1))
	proto.SetExtension(file.Enums[0].Values[0].Desc.Options(), reasonv1.E_Code, code.Code_OK)

	reasons := &Reasons{Domain: "codesjoy.reason.v1.test"}
	require.NoError(t, collectReasons(file.Enums, reasons))
	require.Len(t, reasons.Reason, 1)
	require.Equal(t, "ErrorReason", reasons.Reason[0].Name)
	require.Equal(t, code.Code_OK, reasons.Reason[0].Codes[0].Code)
}

func TestEnumValueCode(t *testing.T) {
	gen, err := newTestPlugin()
	require.NoError(t, err)

	value := gen.Files[0].Enums[0].Values[0]

	t.Run("falls back to unknown without extension", func(t *testing.T) {
		got, err := enumValueCode(value)
		require.NoError(t, err)
		require.Equal(t, code.Code_UNKNOWN, got)
	})

	t.Run("reads enum code extension", func(t *testing.T) {
		proto.SetExtension(value.Desc.Options(), reasonv1.E_Code, code.Code_CANCELLED)

		got, err := enumValueCode(value)
		require.NoError(t, err)
		require.Equal(t, code.Code_CANCELLED, got)
	})
}

func newTestPlugin() (*protogen.Plugin, error) {
	return newTestPluginWithFiles([]string{"test.proto"}, []*descriptorpb.FileDescriptorProto{
		newTestFile("test.proto"),
	})
}

func generatedFileContent(gen *protogen.Plugin, suffix string) string {
	for _, file := range gen.Response().File {
		if strings.HasSuffix(file.GetName(), suffix) {
			return file.GetContent()
		}
	}
	return ""
}

func newTestPluginWithFiles(
	filesToGenerate []string,
	files []*descriptorpb.FileDescriptorProto,
) (*protogen.Plugin, error) {
	return protogen.Options{}.New(&pluginpb.CodeGeneratorRequest{
		FileToGenerate: filesToGenerate,
		ProtoFile:      files,
	})
}

func newTestFile(name string) *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String(name),
		Package: proto.String("codesjoy.reason.v1.test"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String(
				"github.com/codesjoy/pkg/tools/protoc-gen-codesjoy-reason;main",
			),
		},
		EnumType: []*descriptorpb.EnumDescriptorProto{
			newReasonEnum("ErrorReason"),
		},
	}
}

func newReasonEnum(name string) *descriptorpb.EnumDescriptorProto {
	return newReasonEnumWithValue(name, "OK")
}

func newReasonEnumWithValue(name, valueName string) *descriptorpb.EnumDescriptorProto {
	return &descriptorpb.EnumDescriptorProto{
		Name: proto.String(name),
		Value: []*descriptorpb.EnumValueDescriptorProto{
			{
				Name:    proto.String(valueName),
				Number:  proto.Int32(0),
				Options: &descriptorpb.EnumValueOptions{},
			},
		},
		Options: &descriptorpb.EnumOptions{},
	}
}
