package main

import "context"

const generatedHeader = "// Code generated by codesjoy-modelgen. DO NOT EDIT."

const (
	dialectMySQL    = "mysql"
	dialectPostgres = "postgres"
)

const (
	timestampModeUnixSec   = "unix_sec"
	timestampModeUnixMilli = "unix_milli"
	timestampModeUnixNano  = "unix_nano"
)

const (
	softDeleteKindNone   = "none"
	softDeleteKindGORM   = "gorm"
	softDeleteKindPlugin = "plugin"
)

// Introspector defines schema metadata inspection behavior.
type Introspector interface {
	Inspect(
		ctx context.Context,
		dsn string,
		schema string,
		tables []string,
	) ([]TableMeta, error)
}

// TableMeta is the raw metadata for one database table.
type TableMeta struct {
	Schema  string
	Name    string
	Columns []ColumnMeta
	Indexes []IndexMeta
}

// ColumnMeta is the raw metadata for one database column.
type ColumnMeta struct {
	Name            string
	DataType        string
	RawType         string
	Nullable        bool
	DefaultValue    *string
	OrdinalPosition int
	IsPrimaryKey    bool
	IsAutoIncrement bool
	IsIndexed       bool
}

// IndexMeta describes an index and its ordered columns.
type IndexMeta struct {
	Name    string
	Columns []string
}

// ResolvedTable is a table after defaults + overrides are merged.
type ResolvedTable struct {
	Schema           string
	Name             string
	ModelName        string
	AIPSQLBuilder    string
	GenerateAIPTable bool
	TimestampMode    string
	Columns          []ResolvedColumn
	CompositeIndexes []IndexMeta
}

// ResolvedColumn is a column after defaults + overrides are merged.
type ResolvedColumn struct {
	Name             string
	GoField          string
	GoType           string
	JSONName         string
	FieldPath        string
	Filterable       bool
	Sortable         bool
	ImplicitFilter   bool
	BoolType         bool
	KeyValue         bool
	MatchModes       []string
	IndexHint        string
	GormTagAppend    string
	TimestampRole    string
	TimestampMode    string
	UseIntTimestamp  bool
	SoftDeleteKind   string
	HideFromAIPTable bool
	IsPrimaryKey     bool
	IsAutoIncrement  bool
	DataType         string
	RawType          string
	Nullable         bool
}

// RenderedFile is one generated file in memory.
type RenderedFile struct {
	Name    string
	Content []byte
}

// GeneratedFile is one generated file with destination path.
type GeneratedFile struct {
	Path    string
	Content []byte
}

// Renderer converts resolved tables into source files.
type Renderer interface {
	Render(packageName string, tables []ResolvedTable) ([]RenderedFile, error)
}

// FileWriter writes generated files to disk.
type FileWriter interface {
	Write(file GeneratedFile, force bool, dryRun bool) error
}
