// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codesjoy/reason/v1/reason.proto

package reasonv1

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_codesjoy_reason_v1_reason_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "codesjoy.reason.v1.default_reason",
		Tag:           "varint,1108,opt,name=default_reason",
		Filename:      "codesjoy/reason/v1/reason.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*code.Code)(nil),
		Field:         1109,
		Name:          "codesjoy.reason.v1.code",
		Tag:           "varint,1109,opt,name=code,enum=google.rpc.Code",
		Filename:      "codesjoy/reason/v1/reason.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional int32 default_reason = 1108;
	E_DefaultReason = &file_codesjoy_reason_v1_reason_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional google.rpc.Code code = 1109;
	E_Code = &file_codesjoy_reason_v1_reason_proto_extTypes[1]
)

var File_codesjoy_reason_v1_reason_proto protoreflect.FileDescriptor

const file_codesjoy_reason_v1_reason_proto_rawDesc = "" +
	"\n" +
	"\x1fcodesjoy/reason/v1/reason.proto\x12\x12codesjoy.reason.v1\x1a google/protobuf/descriptor.proto\x1a\x15google/rpc/code.proto:D\n" +
	"\x0edefault_reason\x12\x1c.google.protobuf.EnumOptions\x18\xd4\b \x01(\x05R\rdefaultReason:H\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18\xd5\b \x01(\x0e2\x10.google.rpc.CodeR\x04codeB\xca\x01\n" +
	"\x16com.codesjoy.reason.v1B\vReasonProtoP\x01Z9github.com/codesjoy/pkg/proto/codesjoy/reason/v1;reasonv1\xa2\x02\x03CRX\xaa\x02\x12Codesjoy.Reason.V1\xca\x02\x12Codesjoy\\Reason\\V1\xe2\x02\x1eCodesjoy\\Reason\\V1\\GPBMetadata\xea\x02\x14Codesjoy::Reason::V1b\x06proto3"

var file_codesjoy_reason_v1_reason_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil),      // 0: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
	(code.Code)(0),                        // 2: google.rpc.Code
}
var file_codesjoy_reason_v1_reason_proto_depIdxs = []int32{
	0, // 0: codesjoy.reason.v1.default_reason:extendee -> google.protobuf.EnumOptions
	1, // 1: codesjoy.reason.v1.code:extendee -> google.protobuf.EnumValueOptions
	2, // 2: codesjoy.reason.v1.code:type_name -> google.rpc.Code
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codesjoy_reason_v1_reason_proto_init() }
func file_codesjoy_reason_v1_reason_proto_init() {
	if File_codesjoy_reason_v1_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codesjoy_reason_v1_reason_proto_rawDesc), len(file_codesjoy_reason_v1_reason_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_codesjoy_reason_v1_reason_proto_goTypes,
		DependencyIndexes: file_codesjoy_reason_v1_reason_proto_depIdxs,
		ExtensionInfos:    file_codesjoy_reason_v1_reason_proto_extTypes,
	}.Build()
	File_codesjoy_reason_v1_reason_proto = out.File
	file_codesjoy_reason_v1_reason_proto_goTypes = nil
	file_codesjoy_reason_v1_reason_proto_depIdxs = nil
}
